version: "1"

services:
  web:
    image: freebsd:15.0-minimal
    command: /bin/echo "Hello from web service"
    
  api:
    image: freebsd:15.0-minimal
    command: /bin/echo "Hello from API service"
    depends_on:
      - db
      
  db:
    image: freebsd:15.0-minimal
    command: /bin/echo "Database ready"
