/*
 * Lochs Dashboard V3 - Alpine Branded Management UI
 *
 * Complete rewrite with mountain/alpine branding, container create form,
 * terminal/exec, image pull, log search/download/coloring.
 * 6 detail tabs: Overview | Logs | Terminal | Stats | Environment | Mounts
 *
 * Compiled into the binary as static const char[].
 */

#ifndef LOCHS_DASHBOARD_HTML_H
#define LOCHS_DASHBOARD_HTML_H

static const char DASHBOARD_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
"<title>Lochs Dashboard</title>\n"
"<style>\n"
"*{margin:0;padding:0;box-sizing:border-box}\n"
":root{\n"
"  --bg:#0c1222;--bg2:#070d1a;--card:#131c2e;--card2:#182236;--card-hover:#1a2740;\n"
"  --border:#1e2d45;--border2:#162137;--border-focus:#3d7dd8;\n"
"  --text:#e2e8f0;--text2:#8494a7;--text3:#4a5568;\n"
"  --accent:#3d7dd8;--accent2:#5b9bf5;--accent-bg:rgba(61,125,216,.1);\n"
"  --red:#c9372c;--red-bg:rgba(201,55,44,.1);\n"
"  --running:#34d399;--stopped:#6b7280;--created:#60a5fa;\n"
"  --healthy:#34d399;--unhealthy:#f87171;--starting:#fbbf24;\n"
"  --orange:#fb923c;--purple:#a78bfa;--teal:#2dd4bf;\n"
"  --radius:10px;--radius-sm:6px;--radius-lg:14px;\n"
"  --shadow:0 2px 8px rgba(0,0,0,.4);--shadow-lg:0 8px 24px rgba(0,0,0,.5);\n"
"  --sidebar-w:220px;--sidebar-collapsed:60px;--topbar-h:52px\n"
"}\n"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;\n"
"  background:var(--bg);color:var(--text);min-height:100vh;overflow:hidden;font-size:13px;line-height:1.6}\n"
"a{color:var(--accent2);text-decoration:none}\n"
"::-webkit-scrollbar{width:5px;height:5px}\n"
"::-webkit-scrollbar-track{background:transparent}\n"
"::-webkit-scrollbar-thumb{background:var(--border);border-radius:3px}\n"
"::-webkit-scrollbar-thumb:hover{background:var(--text3)}\n"
"\n"
"/* === SIDEBAR === */\n"
".sidebar{position:fixed;left:0;top:0;bottom:0;width:var(--sidebar-w);\n"
"  background:var(--bg2);border-right:1px solid var(--border2);z-index:100;\n"
"  display:flex;flex-direction:column;transition:width .2s ease}\n"
".sidebar.collapsed{width:var(--sidebar-collapsed)}\n"
".sidebar-header{padding:16px;display:flex;align-items:center;gap:10px;\n"
"  border-bottom:1px solid var(--border2);min-height:52px}\n"
".sidebar-logo{display:flex;align-items:center;gap:8px}\n"
".sidebar-logo svg{width:28px;height:28px;flex-shrink:0}\n"
".sidebar-brand{font-size:15px;font-weight:800;letter-spacing:.08em;color:var(--text);\n"
"  white-space:nowrap;overflow:hidden}\n"
".sidebar-brand i{font-style:normal;color:var(--accent);font-weight:600}\n"
".sidebar.collapsed .sidebar-brand{display:none}\n"
".sidebar-nav{flex:1;padding:8px;overflow-y:auto}\n"
".nav-section{font-size:10px;text-transform:uppercase;letter-spacing:.08em;\n"
"  color:var(--text3);padding:12px 12px 4px;font-weight:600}\n"
".sidebar.collapsed .nav-section{display:none}\n"
".nav-item{display:flex;align-items:center;gap:12px;padding:9px 12px;\n"
"  border-radius:var(--radius-sm);color:var(--text2);cursor:pointer;\n"
"  transition:all .15s;font-size:13px;font-weight:500;white-space:nowrap;\n"
"  border-left:3px solid transparent;margin-bottom:1px}\n"
".nav-item:hover{background:rgba(61,125,216,.05);color:var(--text)}\n"
".nav-item.active{background:var(--accent-bg);color:var(--accent2);\n"
"  border-left-color:var(--accent)}\n"
".nav-item svg{width:17px;height:17px;flex-shrink:0;fill:currentColor}\n"
".nav-label{overflow:hidden}\n"
".sidebar.collapsed .nav-label{display:none}\n"
".sidebar.collapsed .nav-item{justify-content:center;padding:9px;border-left:none}\n"
".sidebar-footer{padding:10px 16px;border-top:1px solid var(--border2);\n"
"  font-size:11px;color:var(--text3);display:flex;align-items:center;\n"
"  justify-content:space-between}\n"
".sidebar.collapsed .sidebar-footer span{display:none}\n"
".sidebar-toggle{background:none;border:1px solid var(--border);color:var(--text3);\n"
"  width:26px;height:26px;border-radius:var(--radius-sm);cursor:pointer;\n"
"  display:flex;align-items:center;justify-content:center;flex-shrink:0}\n"
".sidebar-toggle:hover{border-color:var(--text2);color:var(--text)}\n"
".sidebar-toggle svg{width:12px;height:12px;fill:currentColor;transition:transform .2s}\n"
".sidebar.collapsed .sidebar-toggle svg{transform:rotate(180deg)}\n"
".sidebar-mountain{padding:0 8px 8px;opacity:.15}\n"
".sidebar.collapsed .sidebar-mountain{display:none}\n"
"\n"
"/* === MAIN AREA === */\n"
".main{margin-left:var(--sidebar-w);height:100vh;display:flex;flex-direction:column;\n"
"  transition:margin-left .2s ease}\n"
".sidebar.collapsed~.main{margin-left:var(--sidebar-collapsed)}\n"
".topbar{height:var(--topbar-h);padding:0 24px;display:flex;align-items:center;\n"
"  justify-content:space-between;border-bottom:1px solid var(--border);flex-shrink:0;gap:16px}\n"
".topbar-left{display:flex;align-items:center;gap:16px}\n"
".topbar-left h1{font-size:17px;font-weight:700;letter-spacing:-.02em;white-space:nowrap}\n"
".topbar-right{display:flex;align-items:center;gap:8px}\n"
".search-box{position:relative;width:240px}\n"
".search-box input{width:100%;background:var(--bg2);border:1px solid var(--border);\n"
"  color:var(--text);padding:6px 12px 6px 32px;border-radius:var(--radius-sm);\n"
"  font-size:12px;outline:none;transition:border-color .15s}\n"
".search-box input:focus{border-color:var(--accent)}\n"
".search-box input::placeholder{color:var(--text3)}\n"
".search-box svg{position:absolute;left:10px;top:50%;transform:translateY(-50%);\n"
"  width:13px;height:13px;fill:var(--text3)}\n"
".pill{background:var(--card);border:1px solid var(--border);border-radius:20px;\n"
"  padding:3px 10px;font-size:11px;display:flex;align-items:center;gap:5px;white-space:nowrap}\n"
".dot{width:6px;height:6px;border-radius:50%;display:inline-block}\n"
".dot-green{background:var(--running)}\n"
".dot-gray{background:var(--stopped)}\n"
".dot-blue{background:var(--created)}\n"
".icon-btn{background:none;border:1px solid var(--border);color:var(--text3);\n"
"  width:30px;height:30px;border-radius:var(--radius-sm);cursor:pointer;\n"
"  display:flex;align-items:center;justify-content:center;transition:all .15s}\n"
".icon-btn:hover{border-color:var(--accent);color:var(--accent)}\n"
".icon-btn.active{border-color:var(--accent);color:var(--accent);background:var(--accent-bg)}\n"
".icon-btn svg{width:14px;height:14px;fill:currentColor}\n"
".content{flex:1;overflow-y:auto;padding:20px 24px}\n"
".page{display:none}\n"
".page.active{display:block}\n"
"\n"
"/* === DASHBOARD === */\n"
".dash-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:24px}\n"
".dash-stat{background:var(--card);border:1px solid var(--border);border-left:4px solid var(--border);\n"
"  border-radius:var(--radius);padding:16px 18px;display:flex;align-items:center;gap:14px;\n"
"  transition:border-color .15s}\n"
".dash-stat:hover{border-color:var(--border-focus)}\n"
".dash-stat.c-accent{border-left-color:var(--accent)}\n"
".dash-stat.c-green{border-left-color:var(--running)}\n"
".dash-stat.c-orange{border-left-color:var(--orange)}\n"
".dash-stat.c-purple{border-left-color:var(--purple)}\n"
".dash-stat-icon{width:40px;height:40px;border-radius:8px;display:flex;\n"
"  align-items:center;justify-content:center;flex-shrink:0}\n"
".dash-stat-icon svg{width:20px;height:20px;fill:currentColor}\n"
".dash-stat-icon.i-accent{background:var(--accent-bg);color:var(--accent)}\n"
".dash-stat-icon.i-green{background:rgba(52,211,153,.1);color:var(--running)}\n"
".dash-stat-icon.i-orange{background:rgba(251,146,60,.1);color:var(--orange)}\n"
".dash-stat-icon.i-purple{background:rgba(167,139,250,.1);color:var(--purple)}\n"
".dash-stat-body{min-width:0}\n"
".dash-stat-num{font-size:24px;font-weight:700;line-height:1.1}\n"
".dash-stat-label{font-size:12px;color:var(--text2);margin-top:1px}\n"
".dash-stat-sub{font-size:10px;color:var(--text3);margin-top:1px}\n"
".dash-section{margin-bottom:24px}\n"
".section-title{font-size:11px;text-transform:uppercase;letter-spacing:.05em;\n"
"  color:var(--text3);font-weight:600;margin-bottom:10px;display:flex;align-items:center;gap:8px}\n"
".dash-running{display:flex;flex-direction:column;gap:6px}\n"
".dash-run-item{background:var(--card);border:1px solid var(--border);\n"
"  border-left:4px solid var(--running);border-radius:var(--radius);padding:10px 14px;\n"
"  display:flex;align-items:center;justify-content:space-between;cursor:pointer;\n"
"  transition:border-color .15s}\n"
".dash-run-item:hover{border-color:var(--accent)}\n"
".dash-run-left{display:flex;align-items:center;gap:10px}\n"
".dash-run-name{font-weight:600;font-size:13px}\n"
".dash-run-meta{display:flex;gap:10px;font-size:11px;color:var(--text2)}\n"
".dash-sysinfo{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);\n"
"  padding:14px;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}\n"
".sysinfo-item{text-align:center}\n"
".sysinfo-label{font-size:10px;color:var(--text3);text-transform:uppercase;letter-spacing:.5px;font-weight:600}\n"
".sysinfo-val{font-size:13px;margin-top:3px}\n"
"\n"
"/* === TOOLBAR === */\n"
".toolbar{display:flex;align-items:center;justify-content:space-between;\n"
"  margin-bottom:14px;gap:12px;flex-wrap:wrap}\n"
".toolbar-left{display:flex;align-items:center;gap:6px}\n"
".toolbar-right{display:flex;align-items:center;gap:6px}\n"
".filter-pill{background:var(--card);border:1px solid var(--border);color:var(--text2);\n"
"  padding:4px 12px;border-radius:20px;font-size:11px;cursor:pointer;\n"
"  transition:all .15s;font-weight:500}\n"
".filter-pill:hover{border-color:var(--text2);color:var(--text)}\n"
".filter-pill.active{background:var(--accent-bg);border-color:var(--accent);color:var(--accent2)}\n"
".filter-pill .cnt{background:var(--border);padding:1px 5px;border-radius:8px;\n"
"  font-size:10px;margin-left:3px}\n"
".filter-pill.active .cnt{background:var(--accent);color:#fff}\n"
".view-toggle{display:flex;border:1px solid var(--border);border-radius:var(--radius-sm);overflow:hidden}\n"
".view-btn{background:none;border:none;color:var(--text3);padding:4px 8px;\n"
"  cursor:pointer;display:flex;align-items:center}\n"
".view-btn.active{background:var(--accent-bg);color:var(--accent)}\n"
".view-btn svg{width:13px;height:13px;fill:currentColor}\n"
"\n"
"/* === CONTAINER TABLE === */\n"
".c-table{width:100%;border-collapse:collapse}\n"
".c-table th{text-align:left;padding:8px 12px;font-size:10px;font-weight:600;\n"
"  text-transform:uppercase;letter-spacing:.05em;color:var(--text3);\n"
"  border-bottom:1px solid var(--border);cursor:pointer;user-select:none;white-space:nowrap}\n"
".c-table th:hover{color:var(--text2)}\n"
".c-table th .sort-icon{display:inline-block;margin-left:3px;opacity:.4}\n"
".c-table th.sorted .sort-icon{opacity:1;color:var(--accent)}\n"
".c-table td{padding:8px 12px;border-bottom:1px solid var(--border2);font-size:13px;vertical-align:middle}\n"
".c-table tr{cursor:pointer;transition:background .1s}\n"
".c-table tbody tr:hover{background:var(--card)}\n"
".c-table tbody tr:nth-child(even){background:rgba(19,28,46,.4)}\n"
".c-table tbody tr:nth-child(even):hover{background:var(--card)}\n"
".c-table tbody tr{border-left:4px solid transparent}\n"
".c-table tbody tr.row-running{border-left-color:var(--running)}\n"
".c-table tbody tr.row-stopped{border-left-color:var(--stopped)}\n"
".c-table tbody tr.row-created{border-left-color:var(--created)}\n"
".status-dot{width:7px;height:7px;border-radius:50%;display:inline-block}\n"
".status-dot.running{background:var(--running);box-shadow:0 0 6px var(--running)}\n"
".status-dot.stopped{background:var(--stopped)}\n"
".status-dot.created{background:var(--created)}\n"
".badge{padding:2px 7px;border-radius:10px;font-size:10px;font-weight:600;\n"
"  text-transform:uppercase;letter-spacing:.3px;display:inline-block}\n"
".badge-running{background:rgba(52,211,153,.12);color:var(--running)}\n"
".badge-stopped{background:rgba(107,114,128,.15);color:var(--stopped)}\n"
".badge-created{background:rgba(96,165,250,.12);color:var(--created)}\n"
".badge-removed{background:rgba(248,113,113,.12);color:var(--unhealthy)}\n"
".badge-active{background:rgba(52,211,153,.12);color:var(--running)}\n"
".badge-inactive{background:rgba(107,114,128,.15);color:var(--stopped)}\n"
".port-chip{background:var(--bg2);border:1px solid var(--border);padding:1px 5px;\n"
"  border-radius:4px;font-size:10px;font-family:'JetBrains Mono','SF Mono',Consolas,monospace;\n"
"  margin-right:3px;display:inline-block}\n"
".health-dot{width:7px;height:7px;border-radius:50%;display:inline-block;margin-right:3px}\n"
".health-dot.healthy{background:var(--healthy);box-shadow:0 0 6px var(--healthy)}\n"
".health-dot.unhealthy{background:var(--unhealthy);box-shadow:0 0 6px var(--unhealthy)}\n"
".health-dot.starting{background:var(--starting);box-shadow:0 0 6px var(--starting)}\n"
".c-actions{display:flex;gap:4px}\n"
"\n"
"/* === CARD GRID === */\n"
".card-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:14px}\n"
".card{background:var(--card);border:1px solid var(--border);border-left:4px solid var(--stopped);\n"
"  border-radius:var(--radius);padding:16px 18px;transition:all .15s;cursor:pointer;\n"
"  position:relative;overflow:hidden}\n"
".card:hover{border-color:var(--accent);box-shadow:inset 0 1px 0 rgba(255,255,255,.03)}\n"
".card.card-running{border-left-color:var(--running)}\n"
".card.card-stopped{border-left-color:var(--stopped)}\n"
".card.card-created{border-left-color:var(--created)}\n"
".card-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}\n"
".card-name{font-size:15px;font-weight:600}\n"
".card-body{display:grid;grid-template-columns:1fr 1fr;gap:4px 14px;font-size:12px;margin-bottom:12px}\n"
".field{display:flex;gap:6px}\n"
".field .lbl{color:var(--text3);min-width:50px;font-size:11px}\n"
".field .val{color:var(--text);word-break:break-all;font-size:12px}\n"
".card-actions{display:flex;gap:6px;border-top:1px solid var(--border);padding-top:10px}\n"
"\n"
"/* === BUTTONS === */\n"
".btn{background:var(--card);border:1px solid var(--border);color:var(--text);\n"
"  padding:5px 12px;border-radius:var(--radius-sm);font-size:12px;cursor:pointer;\n"
"  transition:all .15s;font-weight:500;display:inline-flex;align-items:center;\n"
"  gap:4px;white-space:nowrap}\n"
".btn:hover{border-color:var(--text2)}\n"
".btn svg{width:12px;height:12px;fill:currentColor}\n"
".btn-sm{padding:3px 8px;font-size:11px}\n"
".btn-start{border-color:rgba(52,211,153,.3);color:var(--running)}\n"
".btn-start:hover{background:rgba(52,211,153,.08);border-color:var(--running)}\n"
".btn-stop{border-color:rgba(248,113,113,.3);color:var(--unhealthy)}\n"
".btn-stop:hover{background:rgba(248,113,113,.08);border-color:var(--unhealthy)}\n"
".btn-danger{background:var(--red-bg);border-color:rgba(201,55,44,.3);color:#f87171}\n"
".btn-danger:hover{background:rgba(201,55,44,.15);border-color:var(--red)}\n"
".btn-primary{background:var(--accent);border-color:var(--accent);color:#fff;font-weight:600}\n"
".btn-primary:hover{background:#3570c4}\n"
".btn:disabled{opacity:.4;cursor:not-allowed;pointer-events:none}\n"
"\n"
"/* === DETAIL PANEL === */\n"
".detail-overlay{display:none;position:fixed;top:0;left:0;right:0;bottom:0;\n"
"  background:rgba(0,0,0,.55);z-index:200;backdrop-filter:blur(3px)}\n"
".detail-overlay.active{display:block}\n"
".detail-panel{position:fixed;top:0;right:0;bottom:0;width:780px;max-width:100vw;\n"
"  background:var(--bg);border-left:1px solid var(--border);z-index:201;\n"
"  display:flex;flex-direction:column;transform:translateX(100%);\n"
"  transition:transform .25s ease;box-shadow:var(--shadow-lg)}\n"
".detail-panel.active{transform:translateX(0)}\n"
".detail-head{display:flex;align-items:center;justify-content:space-between;\n"
"  padding:12px 20px;border-bottom:1px solid var(--border);background:var(--card)}\n"
".detail-head-left{display:flex;align-items:center;gap:10px}\n"
".detail-head h2{font-size:16px;font-weight:700;letter-spacing:-.01em}\n"
".close-btn{background:none;border:1px solid var(--border);color:var(--text3);\n"
"  width:30px;height:30px;border-radius:var(--radius-sm);cursor:pointer;font-size:14px;\n"
"  display:flex;align-items:center;justify-content:center}\n"
".close-btn:hover{border-color:var(--accent);color:var(--accent)}\n"
".detail-tabs{display:flex;gap:0;border-bottom:1px solid var(--border);\n"
"  background:var(--card);padding:0 20px}\n"
".dtab{background:none;border:none;color:var(--text3);padding:9px 14px;\n"
"  font-size:12px;cursor:pointer;border-bottom:2px solid transparent;\n"
"  transition:all .15s;font-weight:500}\n"
".dtab:hover{color:var(--text)}\n"
".dtab.active{color:var(--accent2);border-bottom-color:var(--accent)}\n"
".detail-body{flex:1;overflow-y:auto;padding:20px}\n"
".dcontent{display:none}\n"
".dcontent.active{display:block}\n"
".info-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}\n"
".info-item{background:var(--card);border:1px solid var(--border);border-radius:var(--radius-sm);padding:10px 12px}\n"
".info-item .il{color:var(--text3);font-size:10px;text-transform:uppercase;\n"
"  letter-spacing:.05em;margin-bottom:3px;font-weight:600}\n"
".info-item .iv{font-size:13px;word-break:break-all}\n"
".info-full{grid-column:1/-1}\n"
"\n"
"/* === TERMINAL TAB === */\n"
".term-wrap{display:flex;flex-direction:column;height:100%}\n"
".term-output{background:var(--bg2);border:1px solid var(--border);border-radius:var(--radius-sm);\n"
"  padding:12px;font-family:'JetBrains Mono','SF Mono',Consolas,monospace;\n"
"  font-size:12px;line-height:1.7;color:var(--running);height:400px;overflow-y:auto;\n"
"  white-space:pre-wrap;word-break:break-all;flex:1}\n"
".term-output .term-cmd{color:var(--accent2)}\n"
".term-output .term-err{color:var(--unhealthy)}\n"
".term-input-row{display:flex;gap:8px;margin-top:10px;align-items:center}\n"
".term-prompt{color:var(--running);font-family:'JetBrains Mono','SF Mono',Consolas,monospace;\n"
"  font-size:13px;font-weight:700;flex-shrink:0}\n"
".term-input{flex:1;background:var(--bg2);border:1px solid var(--border);color:var(--text);\n"
"  padding:8px 12px;border-radius:var(--radius-sm);font-family:'JetBrains Mono','SF Mono',Consolas,monospace;\n"
"  font-size:12px;outline:none}\n"
".term-input:focus{border-color:var(--accent)}\n"
".term-disabled{opacity:.5;text-align:center;padding:40px;color:var(--text3)}\n"
"\n"
"/* === LOG VIEWER === */\n"
".log-controls{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px;gap:8px}\n"
".log-controls-left{display:flex;align-items:center;gap:8px}\n"
".log-search{background:var(--bg2);border:1px solid var(--border);color:var(--text);\n"
"  padding:5px 10px;border-radius:var(--radius-sm);font-size:12px;outline:none;width:200px}\n"
".log-search:focus{border-color:var(--accent)}\n"
".log-badge{background:var(--accent-bg);color:var(--accent);padding:2px 8px;\n"
"  border-radius:10px;font-size:10px;font-weight:600}\n"
".log-viewer{background:var(--bg2);border:1px solid var(--border);border-radius:var(--radius-sm);\n"
"  padding:12px;font-family:'JetBrains Mono','SF Mono',Consolas,monospace;\n"
"  font-size:11px;line-height:1.7;color:var(--text2);height:420px;overflow-y:auto;\n"
"  white-space:pre-wrap;word-break:break-all}\n"
".log-line{display:flex;gap:10px}\n"
".log-num{color:var(--text3);min-width:28px;text-align:right;user-select:none;font-size:10px}\n"
".log-text{flex:1}\n"
".log-error{color:var(--unhealthy)}\n"
".log-warn{color:var(--starting)}\n"
".log-info{color:var(--accent2)}\n"
"\n"
"/* === STATS === */\n"
".stats-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}\n"
".stat-card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);padding:18px;text-align:center}\n"
".stat-label{color:var(--text3);font-size:10px;text-transform:uppercase;\n"
"  letter-spacing:.05em;margin-bottom:8px;font-weight:600}\n"
".stat-ring{position:relative;width:90px;height:90px;margin:0 auto 8px}\n"
".stat-ring svg{transform:rotate(-90deg)}\n"
".stat-ring-text{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:16px;font-weight:700}\n"
".stat-value{font-size:20px;font-weight:700}\n"
".stat-sub{color:var(--text2);font-size:11px;margin-top:3px}\n"
"\n"
"/* === ENV/MOUNT TABLES === */\n"
".env-table,.mount-table{width:100%;border-collapse:collapse}\n"
".env-table th,.mount-table th{text-align:left;padding:7px 12px;font-size:10px;font-weight:600;\n"
"  text-transform:uppercase;letter-spacing:.05em;color:var(--text3);\n"
"  border-bottom:1px solid var(--border);background:var(--card)}\n"
".env-table td,.mount-table td{padding:7px 12px;font-size:12px;border-bottom:1px solid var(--border2);\n"
"  font-family:'JetBrains Mono','SF Mono',Consolas,monospace}\n"
".env-table tr:nth-child(even) td,.mount-table tr:nth-child(even) td{background:rgba(19,28,46,.3)}\n"
".ro-badge{background:rgba(251,146,60,.12);color:var(--orange);padding:1px 5px;\n"
"  border-radius:4px;font-size:10px;font-weight:600}\n"
".rw-badge{background:rgba(52,211,153,.12);color:var(--running);padding:1px 5px;\n"
"  border-radius:4px;font-size:10px;font-weight:600}\n"
"\n"
"/* === DATA TABLES === */\n"
".data-table{width:100%;border-collapse:collapse}\n"
".data-table th{text-align:left;padding:8px 12px;font-size:10px;font-weight:600;\n"
"  text-transform:uppercase;letter-spacing:.05em;color:var(--text3);border-bottom:1px solid var(--border)}\n"
".data-table td{padding:8px 12px;font-size:13px;border-bottom:1px solid var(--border2);vertical-align:middle}\n"
".data-table tbody tr{transition:background .1s}\n"
".data-table tbody tr:hover{background:var(--card)}\n"
".data-table tbody tr:nth-child(even){background:rgba(19,28,46,.3)}\n"
".data-table tbody tr:nth-child(even):hover{background:var(--card)}\n"
".mono{font-family:'JetBrains Mono','SF Mono',Consolas,monospace;font-size:11px}\n"
".text-muted{color:var(--text2)}\n"
".hint-box{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);\n"
"  padding:12px;margin-top:14px;font-size:12px;color:var(--text2)}\n"
".hint-box code{background:var(--bg2);padding:2px 5px;border-radius:3px;\n"
"  font-family:'JetBrains Mono','SF Mono',Consolas,monospace;font-size:11px;color:var(--text)}\n"
"\n"
"/* === CREATE PANEL === */\n"
".create-overlay{display:none;position:fixed;top:0;left:0;right:0;bottom:0;\n"
"  background:rgba(0,0,0,.55);z-index:300;backdrop-filter:blur(3px)}\n"
".create-overlay.active{display:block}\n"
".create-panel{position:fixed;top:0;right:0;bottom:0;width:520px;max-width:100vw;\n"
"  background:var(--bg);border-left:1px solid var(--border);z-index:301;\n"
"  display:flex;flex-direction:column;transform:translateX(100%);\n"
"  transition:transform .25s ease;box-shadow:var(--shadow-lg)}\n"
".create-panel.active{transform:translateX(0)}\n"
".create-head{display:flex;align-items:center;justify-content:space-between;\n"
"  padding:14px 20px;border-bottom:1px solid var(--border);background:var(--card)}\n"
".create-head h2{font-size:16px;font-weight:700}\n"
".create-body{flex:1;overflow-y:auto;padding:20px}\n"
".create-footer{padding:14px 20px;border-top:1px solid var(--border);\n"
"  display:flex;gap:8px;justify-content:flex-end;background:var(--card)}\n"
".form-group{margin-bottom:16px}\n"
".form-label{display:block;font-size:11px;font-weight:600;color:var(--text2);\n"
"  text-transform:uppercase;letter-spacing:.04em;margin-bottom:5px}\n"
".form-input{width:100%;background:var(--bg2);border:1px solid var(--border);color:var(--text);\n"
"  padding:8px 12px;border-radius:var(--radius-sm);font-size:13px;outline:none}\n"
".form-input:focus{border-color:var(--accent)}\n"
".form-select{width:100%;background:var(--bg2);border:1px solid var(--border);color:var(--text);\n"
"  padding:8px 12px;border-radius:var(--radius-sm);font-size:13px;outline:none;\n"
"  appearance:none;cursor:pointer}\n"
".form-row{display:flex;gap:8px;align-items:center;margin-bottom:6px}\n"
".form-row input{flex:1}\n"
".form-row .form-arrow{color:var(--text3);font-size:13px;flex-shrink:0}\n"
".form-add-btn{background:none;border:1px dashed var(--border);color:var(--text3);\n"
"  padding:5px 12px;border-radius:var(--radius-sm);font-size:11px;cursor:pointer;\n"
"  width:100%;transition:all .15s}\n"
".form-add-btn:hover{border-color:var(--accent);color:var(--accent)}\n"
".form-remove{background:none;border:none;color:var(--text3);cursor:pointer;\n"
"  font-size:16px;padding:0 4px;line-height:1}\n"
".form-remove:hover{color:var(--unhealthy)}\n"
".form-section{font-size:12px;font-weight:600;color:var(--text);margin:20px 0 10px;\n"
"  padding-bottom:6px;border-bottom:1px solid var(--border)}\n"
".form-row-small{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px}\n"
".form-check{display:flex;align-items:center;gap:8px;margin-top:12px;font-size:13px;cursor:pointer}\n"
".form-check input{accent-color:var(--accent)}\n"
"\n"
"/* === PULL MODAL === */\n"
".pull-overlay{display:none;position:fixed;top:0;left:0;right:0;bottom:0;\n"
"  background:rgba(0,0,0,.6);z-index:300;backdrop-filter:blur(3px);\n"
"  align-items:center;justify-content:center}\n"
".pull-overlay.active{display:flex}\n"
".pull-modal{background:var(--card);border:1px solid var(--border);border-radius:var(--radius-lg);\n"
"  padding:24px;width:440px;max-width:90vw;box-shadow:var(--shadow-lg)}\n"
".pull-modal h3{font-size:16px;font-weight:700;margin-bottom:4px}\n"
".pull-modal .pull-sub{font-size:12px;color:var(--text2);margin-bottom:16px}\n"
".pull-status{margin-top:12px;font-size:12px;color:var(--text2);display:none;\n"
"  align-items:center;gap:8px}\n"
".pull-status.active{display:flex}\n"
"\n"
"/* === CONFIRM MODAL === */\n"
".modal-overlay{display:none;position:fixed;top:0;left:0;right:0;bottom:0;\n"
"  background:rgba(0,0,0,.6);z-index:400;backdrop-filter:blur(3px);\n"
"  align-items:center;justify-content:center}\n"
".modal-overlay.active{display:flex}\n"
".modal{background:var(--card);border:1px solid var(--border);border-radius:var(--radius-lg);\n"
"  padding:24px;width:420px;max-width:90vw;box-shadow:var(--shadow-lg)}\n"
".modal h3{font-size:16px;margin-bottom:6px}\n"
".modal p{font-size:13px;color:var(--text2);margin-bottom:18px}\n"
".modal-actions{display:flex;gap:8px;justify-content:flex-end}\n"
"\n"
"/* === TOAST === */\n"
".toast-container{position:fixed;bottom:20px;right:20px;z-index:500;\n"
"  display:flex;flex-direction:column-reverse;gap:6px}\n"
".toast{padding:10px 16px;border-radius:var(--radius);font-size:12px;\n"
"  transform:translateX(120%);opacity:0;transition:all .3s ease;\n"
"  display:flex;align-items:center;gap:6px;box-shadow:var(--shadow-lg);max-width:340px}\n"
".toast.show{transform:translateX(0);opacity:1}\n"
".toast.ok{background:rgba(52,211,153,.9);color:#fff}\n"
".toast.err{background:rgba(201,55,44,.9);color:#fff}\n"
".toast.info{background:rgba(61,125,216,.9);color:#fff}\n"
"\n"
"/* === EMPTY STATE === */\n"
".empty{text-align:center;padding:50px 20px;color:var(--text2)}\n"
".empty svg{width:64px;height:64px;fill:var(--text3);opacity:.4;margin-bottom:12px}\n"
".empty h3{font-size:16px;margin-bottom:6px;color:var(--text);font-weight:600}\n"
".empty p{font-size:13px}\n"
".empty code{background:var(--bg2);padding:2px 6px;border-radius:3px;\n"
"  font-family:'JetBrains Mono','SF Mono',Consolas,monospace;font-size:11px;color:var(--accent2)}\n"
"\n"
"/* === SPINNER === */\n"
"@keyframes spin{to{transform:rotate(360deg)}}\n"
".spinner{width:14px;height:14px;border:2px solid var(--border);border-top-color:var(--accent);\n"
"  border-radius:50%;animation:spin .6s linear infinite;display:inline-block}\n"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}\n"
".pulse{animation:pulse 2s ease-in-out infinite}\n"
"\n"
"/* === RESPONSIVE === */\n"
"@media(max-width:1200px){\n"
"  .sidebar{width:var(--sidebar-collapsed)}\n"
"  .sidebar .nav-label,.sidebar .sidebar-brand,.sidebar-footer span,.sidebar-mountain,.nav-section{display:none}\n"
"  .sidebar .nav-item{justify-content:center;padding:9px;border-left:none}\n"
"  .main{margin-left:var(--sidebar-collapsed)}\n"
"  .dash-stats{grid-template-columns:repeat(2,1fr)}\n"
"}\n"
"@media(max-width:768px){\n"
"  .sidebar{display:none}.main{margin-left:0}\n"
"  .card-grid{grid-template-columns:1fr}.detail-panel,.create-panel{width:100vw}\n"
"  .info-grid,.stats-grid{grid-template-columns:1fr}\n"
"  .dash-stats{grid-template-columns:1fr}.content{padding:14px 12px}\n"
"  .dash-sysinfo{grid-template-columns:1fr}.topbar{padding:0 12px}\n"
"  .search-box{width:140px}\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<!-- Sidebar -->\n"
"<nav id=\"sidebar\" class=\"sidebar\">\n"
"  <div class=\"sidebar-header\">\n"
"    <div class=\"sidebar-logo\">\n"
"      <svg viewBox=\"0 0 32 32\" fill=\"none\"><path d=\"M4 28L10 16L14 20L20 8L24 14L28 4\" stroke=\"#3d7dd8\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 28L10 16L14 20L20 8L24 14L28 4\" stroke=\"#c9372c\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-dasharray=\"2 4\" opacity=\".3\"/></svg>\n"
"      <span class=\"sidebar-brand\">LOCHS<i>.dev</i></span>\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"sidebar-nav\">\n"
"    <div class=\"nav-section\">Overview</div>\n"
"    <div class=\"nav-item active\" onclick=\"navigate('dashboard')\" data-page=\"dashboard\">\n"
"      <svg viewBox=\"0 0 24 24\"><path d=\"M3 13h8V3H3v10zm0 8h8v-6H3v6zm10 0h8V11h-8v10zm0-18v6h8V3h-8z\"/></svg>\n"
"      <span class=\"nav-label\">Dashboard</span>\n"
"    </div>\n"
"    <div class=\"nav-section\">Resources</div>\n"
"    <div class=\"nav-item\" onclick=\"navigate('containers')\" data-page=\"containers\">\n"
"      <svg viewBox=\"0 0 24 24\"><path d=\"M21 3H3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H3V5h18v14zM5 15h14v2H5zm0-4h14v2H5zm0-4h14v2H5z\"/></svg>\n"
"      <span class=\"nav-label\">Containers</span>\n"
"    </div>\n"
"    <div class=\"nav-item\" onclick=\"navigate('images')\" data-page=\"images\">\n"
"      <svg viewBox=\"0 0 24 24\"><path d=\"M22 13h-8v-2h8v2zm0-6h-8v2h8V7zm-8 10h8v-2h-8v2zm-2-4V5c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v8c0 1.1.9 2 2 2h6c1.1 0 2-.9 2-2zm-1.5-1l-2.25-3-1.75 2.26-1.25-1.51L3.5 14h7z\"/></svg>\n"
"      <span class=\"nav-label\">Images</span>\n"
"    </div>\n"
"    <div class=\"nav-item\" onclick=\"navigate('volumes')\" data-page=\"volumes\">\n"
"      <svg viewBox=\"0 0 24 24\"><path d=\"M2 20h20v-4H2v4zm2-3h2v2H4v-2zM2 4v4h20V4H2zm4 3H4V5h2v2zm-4 7h20v-4H2v4zm2-3h2v2H4v-2z\"/></svg>\n"
"      <span class=\"nav-label\">Volumes</span>\n"
"    </div>\n"
"    <div class=\"nav-item\" onclick=\"navigate('networks')\" data-page=\"networks\">\n"
"      <svg viewBox=\"0 0 24 24\"><path d=\"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z\"/></svg>\n"
"      <span class=\"nav-label\">Networks</span>\n"
"    </div>\n"
"    <div class=\"nav-item\" onclick=\"navigate('build')\" data-page=\"build\">\n"
"      <svg viewBox=\"0 0 24 24\"><path d=\"M22 6c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6zm-2 0l-8 5-8-5h16zm0 12H4V8l8 5 8-5v10z\"/></svg>\n"
"      <span class=\"nav-label\">Build</span>\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"sidebar-mountain\">\n"
"    <svg viewBox=\"0 0 200 50\" fill=\"none\" width=\"100%\">\n"
"      <path d=\"M0,50 L20,30 L35,38 L60,15 L80,28 L95,10 L115,25 L135,5 L155,22 L170,12 L190,30 L200,20 L200,50Z\"\n"
"        fill=\"#3d7dd8\" opacity=\".15\"/>\n"
"      <path d=\"M0,50 L30,35 L50,42 L75,22 L100,35 L130,18 L160,32 L200,15 L200,50Z\"\n"
"        fill=\"#3d7dd8\" opacity=\".08\"/>\n"
"    </svg>\n"
"  </div>\n"
"  <div class=\"sidebar-footer\">\n"
"    <span id=\"sidebar-version\"></span>\n"
"    <button class=\"sidebar-toggle\" onclick=\"toggleSidebar()\">\n"
"      <svg viewBox=\"0 0 24 24\"><path d=\"M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z\"/></svg>\n"
"    </button>\n"
"  </div>\n"
"</nav>\n"
"\n"
"<!-- Main -->\n"
"<div class=\"main\">\n"
"  <div class=\"topbar\">\n"
"    <div class=\"topbar-left\"><h1 id=\"page-title\">Dashboard</h1></div>\n"
"    <div class=\"topbar-right\">\n"
"      <div class=\"search-box\" id=\"search-wrap\" style=\"display:none\">\n"
"        <svg viewBox=\"0 0 24 24\"><path d=\"M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z\"/></svg>\n"
"        <input type=\"text\" id=\"search-input\" placeholder=\"Search containers...\" oninput=\"onSearch(this.value)\">\n"
"      </div>\n"
"      <div class=\"pill\"><span class=\"dot dot-green\"></span><span id=\"s-run\">0</span> running</div>\n"
"      <div class=\"pill\"><span class=\"dot dot-gray\"></span><span id=\"s-stop\">0</span> stopped</div>\n"
"      <button class=\"icon-btn\" id=\"refresh-btn\" onclick=\"manualRefresh()\" title=\"Refresh\">\n"
"        <svg viewBox=\"0 0 24 24\"><path d=\"M17.65 6.35C16.2 4.9 14.21 4 12 4c-4.42 0-7.99 3.58-7.99 8s3.57 8 7.99 8c3.73 0 6.84-2.55 7.73-6h-2.08c-.82 2.33-3.04 4-5.65 4-3.31 0-6-2.69-6-6s2.69-6 6-6c1.66 0 3.14.69 4.22 1.78L13 11h7V4l-2.35 2.35z\"/></svg>\n"
"      </button>\n"
"      <button class=\"icon-btn\" id=\"auto-btn\" onclick=\"toggleAuto()\" title=\"Auto-refresh\">\n"
"        <svg viewBox=\"0 0 24 24\"><path d=\"M12 4V1L8 5l4 4V6c3.31 0 6 2.69 6 6 0 1.01-.25 1.97-.7 2.8l1.46 1.46C19.54 15.03 20 13.57 20 12c0-4.42-3.58-8-8-8zm0 14c-3.31 0-6-2.69-6-6 0-1.01.25-1.97.7-2.8L5.24 7.74C4.46 8.97 4 10.43 4 12c0 4.42 3.58 8 8 8v3l4-4-4-4v3z\"/></svg>\n"
"      </button>\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"content\">\n"
"    <!-- Dashboard page -->\n"
"    <div id=\"pg-dashboard\" class=\"page active\">\n"
"      <div class=\"dash-stats\" id=\"dash-stats\"></div>\n"
"      <div class=\"dash-section\">\n"
"        <div class=\"section-title\"><span class=\"dot dot-green\"></span> Running Containers</div>\n"
"        <div class=\"dash-running\" id=\"dash-running\"></div>\n"
"      </div>\n"
"      <div class=\"dash-section\" style=\"margin-top:16px\">\n"
"        <div class=\"section-title\">System Information</div>\n"
"        <div class=\"dash-sysinfo\" id=\"dash-sysinfo\"></div>\n"
"      </div>\n"
"    </div>\n"
"    <!-- Containers page -->\n"
"    <div id=\"pg-containers\" class=\"page\">\n"
"      <div class=\"toolbar\">\n"
"        <div class=\"toolbar-left\" id=\"filter-pills\"></div>\n"
"        <div class=\"toolbar-right\">\n"
"          <button class=\"btn btn-primary\" onclick=\"openCreate()\">+ New Container</button>\n"
"          <div class=\"view-toggle\">\n"
"            <button class=\"view-btn active\" id=\"vt-table\" onclick=\"setView('table')\" title=\"Table\">\n"
"              <svg viewBox=\"0 0 24 24\"><path d=\"M3 14h4v-4H3v4zm0 5h4v-4H3v4zM3 9h4V5H3v4zm5 5h14v-4H8v4zm0 5h14v-4H8v4zM8 5v4h14V5H8z\"/></svg>\n"
"            </button>\n"
"            <button class=\"view-btn\" id=\"vt-grid\" onclick=\"setView('grid')\" title=\"Grid\">\n"
"              <svg viewBox=\"0 0 24 24\"><path d=\"M4 11h5V5H4v6zm0 7h5v-6H4v6zm6 0h5v-6h-5v6zm6 0h5v-6h-5v6zm-6-7h5V5h-5v6zm6-6v6h5V5h-5z\"/></svg>\n"
"            </button>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"      <div id=\"containers-view\"></div>\n"
"    </div>\n"
"    <!-- Images page -->\n"
"    <div id=\"pg-images\" class=\"page\">\n"
"      <div class=\"toolbar\">\n"
"        <div class=\"toolbar-left\"><div class=\"section-title\" style=\"margin:0\">Local Images</div></div>\n"
"        <div class=\"toolbar-right\">\n"
"          <button class=\"btn btn-primary\" onclick=\"openPull()\">Pull Image</button>\n"
"        </div>\n"
"      </div>\n"
"      <div id=\"images-view\"></div>\n"
"    </div>\n"
"    <!-- Volumes page -->\n"
"    <div id=\"pg-volumes\" class=\"page\">\n"
"      <div class=\"toolbar\"><div class=\"toolbar-left\"><div class=\"section-title\" style=\"margin:0\">Named Volumes</div></div>\n"
"        <div class=\"toolbar-right\"><button class=\"btn btn-primary\" onclick=\"openVolCreate()\">+ Create Volume</button></div></div>\n"
"      <div id=\"volumes-view\"></div>\n"
"    </div>\n"
"    <!-- Networks page -->\n"
"    <div id=\"pg-networks\" class=\"page\">\n"
"      <div class=\"toolbar\"><div class=\"toolbar-left\"><div class=\"section-title\" style=\"margin:0\">Container Networks</div></div>\n"
"        <div class=\"toolbar-right\"><button class=\"btn btn-primary\" onclick=\"openNetCreate()\">+ Create Network</button></div></div>\n"
"      <div id=\"networks-view\"></div>\n"
"    </div>\n"
"    <!-- Build page -->\n"
"    <div id=\"pg-build\" class=\"page\">\n"
"      <div class=\"toolbar\"><div class=\"toolbar-left\"><div class=\"section-title\" style=\"margin:0\">Build from Lochfile</div></div>\n"
"        <div class=\"toolbar-right\">\n"
"          <select class=\"form-select\" id=\"bf-template\" onchange=\"loadTemplate()\" style=\"width:200px;padding:5px 10px;font-size:12px\">\n"
"            <option value=\"\">Template...</option><option value=\"basic\">Basic FreeBSD</option>\n"
"            <option value=\"nginx\">Nginx Server</option><option value=\"node\">Node.js App</option>\n"
"          </select>\n"
"          <button class=\"btn btn-primary\" onclick=\"submitBuild()\">Build</button>\n"
"        </div></div>\n"
"      <div style=\"display:flex;gap:8px;margin-bottom:10px;align-items:center\">\n"
"        <label class=\"form-label\" style=\"margin:0;white-space:nowrap\">Tag:</label>\n"
"        <input class=\"form-input\" id=\"bf-tag\" placeholder=\"myimage:latest\" style=\"width:220px;padding:5px 10px;font-size:12px\">\n"
"      </div>\n"
"      <textarea id=\"bf-editor\" style=\"width:100%;height:420px;background:var(--bg2);color:var(--running);\n"
"        border:1px solid var(--border);border-radius:var(--radius-sm);padding:14px;\n"
"        font-family:'JetBrains Mono','SF Mono',Consolas,monospace;font-size:12px;line-height:1.7;\n"
"        resize:vertical;outline:none;tab-size:4\" placeholder=\"FROM freebsd:15\\nRUN pkg install -y nginx\\nCMD nginx -g 'daemon off;'\" spellcheck=\"false\"></textarea>\n"
"      <div id=\"build-output\" style=\"display:none;margin-top:12px;background:var(--bg2);border:1px solid var(--border);\n"
"        border-radius:var(--radius-sm);padding:14px;font-family:'JetBrains Mono','SF Mono',Consolas,monospace;\n"
"        font-size:11px;line-height:1.7;color:var(--text2);max-height:200px;overflow-y:auto;white-space:pre-wrap\"></div>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<!-- Detail panel -->\n"
"<div id=\"overlay\" class=\"detail-overlay\" onclick=\"closeDetail()\"></div>\n"
"<div id=\"detail\" class=\"detail-panel\">\n"
"  <div class=\"detail-head\">\n"
"    <div class=\"detail-head-left\">\n"
"      <span id=\"d-status-dot\" class=\"status-dot\"></span>\n"
"      <h2 id=\"d-name\"></h2>\n"
"      <span id=\"d-badge\" class=\"badge\"></span>\n"
"    </div>\n"
"    <button class=\"close-btn\" onclick=\"closeDetail()\">&#10005;</button>\n"
"  </div>\n"
"  <div class=\"detail-tabs\">\n"
"    <button class=\"dtab active\" onclick=\"showDTab('overview')\">Overview</button>\n"
"    <button class=\"dtab\" onclick=\"showDTab('logs')\">Logs</button>\n"
"    <button class=\"dtab\" onclick=\"showDTab('terminal')\">Terminal</button>\n"
"    <button class=\"dtab\" onclick=\"showDTab('stats')\">Stats</button>\n"
"    <button class=\"dtab\" onclick=\"showDTab('env')\">Environment</button>\n"
"    <button class=\"dtab\" onclick=\"showDTab('mounts')\">Mounts</button>\n"
"  </div>\n"
"  <div class=\"detail-body\">\n"
"    <div id=\"d-overview\" class=\"dcontent active\"></div>\n"
"    <div id=\"d-logs\" class=\"dcontent\"></div>\n"
"    <div id=\"d-terminal\" class=\"dcontent\"></div>\n"
"    <div id=\"d-stats\" class=\"dcontent\"></div>\n"
"    <div id=\"d-env\" class=\"dcontent\"></div>\n"
"    <div id=\"d-mounts\" class=\"dcontent\"></div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<!-- Create panel -->\n"
"<div id=\"create-overlay\" class=\"create-overlay\" onclick=\"closeCreate()\"></div>\n"
"<div id=\"create-panel\" class=\"create-panel\">\n"
"  <div class=\"create-head\">\n"
"    <h2>New Container</h2>\n"
"    <button class=\"close-btn\" onclick=\"closeCreate()\">&#10005;</button>\n"
"  </div>\n"
"  <div class=\"create-body\">\n"
"    <div class=\"form-group\">\n"
"      <label class=\"form-label\">Container Name</label>\n"
"      <input class=\"form-input\" id=\"cf-name\" placeholder=\"my-container\">\n"
"    </div>\n"
"    <div class=\"form-group\">\n"
"      <label class=\"form-label\">Image</label>\n"
"      <select class=\"form-select\" id=\"cf-image\"><option value=\"\">Select an image...</option></select>\n"
"    </div>\n"
"    <div class=\"form-section\">Port Mappings</div>\n"
"    <div id=\"cf-ports\"></div>\n"
"    <button class=\"form-add-btn\" onclick=\"addPort()\">+ Add Port Mapping</button>\n"
"    <div class=\"form-section\">Environment Variables</div>\n"
"    <div id=\"cf-envs\"></div>\n"
"    <button class=\"form-add-btn\" onclick=\"addEnv()\">+ Add Variable</button>\n"
"    <div class=\"form-section\">Resource Limits</div>\n"
"    <div class=\"form-row-small\">\n"
"      <div class=\"form-group\"><label class=\"form-label\">CPU (cores)</label>\n"
"        <input class=\"form-input\" id=\"cf-cpu\" placeholder=\"0.5\" type=\"number\" step=\"0.1\" min=\"0\"></div>\n"
"      <div class=\"form-group\"><label class=\"form-label\">Memory (MB)</label>\n"
"        <input class=\"form-input\" id=\"cf-mem\" placeholder=\"512\" type=\"number\" min=\"0\"></div>\n"
"      <div class=\"form-group\"><label class=\"form-label\">PID Limit</label>\n"
"        <input class=\"form-input\" id=\"cf-pids\" placeholder=\"\" type=\"number\" min=\"0\"></div>\n"
"    </div>\n"
"    <label class=\"form-check\"><input type=\"checkbox\" id=\"cf-start\" checked> Start after creation</label>\n"
"  </div>\n"
"  <div class=\"create-footer\">\n"
"    <button class=\"btn\" onclick=\"closeCreate()\">Cancel</button>\n"
"    <button class=\"btn btn-primary\" id=\"cf-submit\" onclick=\"submitCreate()\">Create Container</button>\n"
"  </div>\n"
"</div>\n"
"\n"
"<!-- Pull modal -->\n"
"<div id=\"pull-overlay\" class=\"pull-overlay\">\n"
"  <div class=\"pull-modal\">\n"
"    <h3>Pull Image</h3>\n"
"    <p class=\"pull-sub\">Download an image from the registry</p>\n"
"    <div class=\"form-group\">\n"
"      <label class=\"form-label\">Image Name</label>\n"
"      <input class=\"form-input\" id=\"pull-input\" placeholder=\"freebsd:15\">\n"
"    </div>\n"
"    <div class=\"pull-status\" id=\"pull-status\"><span class=\"spinner\"></span><span id=\"pull-status-text\">Pulling...</span></div>\n"
"    <div style=\"display:flex;gap:8px;justify-content:flex-end;margin-top:16px\">\n"
"      <button class=\"btn\" onclick=\"closePull()\">Cancel</button>\n"
"      <button class=\"btn btn-primary\" id=\"pull-btn\" onclick=\"submitPull()\">Pull</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<!-- Confirm modal -->\n"
"<div id=\"modal-overlay\" class=\"modal-overlay\">\n"
"  <div class=\"modal\">\n"
"    <h3 id=\"modal-title\"></h3>\n"
"    <p id=\"modal-msg\"></p>\n"
"    <div class=\"modal-actions\">\n"
"      <button class=\"btn\" onclick=\"closeModal()\">Cancel</button>\n"
"      <button class=\"btn btn-danger\" id=\"modal-confirm\" onclick=\"confirmModal()\">Confirm</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<!-- Login modal -->\n"
"<div id=\"login-overlay\" class=\"modal-overlay\" style=\"z-index:9999\">\n"
"  <div class=\"modal\" style=\"max-width:360px\">\n"
"    <h3 style=\"margin-bottom:12px\">\xf0\x9f\x94\x92 Authentication Required</h3>\n"
"    <p style=\"color:var(--text2);margin-bottom:14px;font-size:12px\">\n"
"      Enter the dashboard token from the server console.</p>\n"
"    <input type=\"password\" id=\"login-token\" placeholder=\"Paste token here\"\n"
"      style=\"width:100%;background:var(--bg2);border:1px solid var(--border);\n"
"      color:var(--text);padding:8px 12px;border-radius:var(--radius-sm);\n"
"      font-size:13px;outline:none;margin-bottom:10px\"\n"
"      onkeydown=\"if(event.key==='Enter')doLogin()\">\n"
"    <p id=\"login-error\" style=\"color:var(--red);font-size:11px;margin-bottom:8px;display:none\"></p>\n"
"    <div class=\"modal-actions\">\n"
"      <button class=\"btn btn-primary\" onclick=\"doLogin()\">Login</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<!-- Toasts -->\n"
"<div id=\"toasts\" class=\"toast-container\"></div>\n"
"\n"
"<script>\n"
"/* STATE */\n"
"const S={\n"
"  page:'dashboard',containers:[],images:[],system:{},\n"
"  view:localStorage.getItem('lochs-view')||'table',\n"
"  search:'',stateFilter:'all',sortBy:'name',sortDir:'asc',\n"
"  detail:null,detailTab:'overview',detailData:null,\n"
"  autoRefresh:true,refreshTimer:null,logTimer:null,statsTimer:null,\n"
"  modalCb:null,termHistory:[],logSearch:'',logLines:[]\n"
"};\n"
"\n"
"/* AUTH */\n"
"function getToken(){return localStorage.getItem('lochs-token')||''}\n"
"function setToken(t){localStorage.setItem('lochs-token',t)}\n"
"function showLogin(){$('login-overlay').classList.add('active');$('login-token').focus()}\n"
"function hideLogin(){$('login-overlay').classList.remove('active')}\n"
"async function doLogin(){\n"
"  const t=$('login-token').value.trim();\n"
"  if(!t)return;\n"
"  try{\n"
"    const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},\n"
"      body:JSON.stringify({token:t})});\n"
"    if(r.ok){setToken(t);hideLogin();$('login-error').style.display='none';refreshAll()}\n"
"    else{$('login-error').textContent='Invalid token';$('login-error').style.display='block'}\n"
"  }catch(e){$('login-error').textContent='Connection error';$('login-error').style.display='block'}\n"
"}\n"
"\n"
"/* HELPERS */\n"
"async function api(path,opts){\n"
"  try{\n"
"    if(!opts)opts={};\n"
"    if(!opts.headers)opts.headers={};\n"
"    const tok=getToken();\n"
"    if(tok)opts.headers['Authorization']='Bearer '+tok;\n"
"    const r=await fetch(path,opts);\n"
"    if(r.status===401){showLogin();return null}\n"
"    return await r.json()\n"
"  }catch(e){return null}\n"
"}\n"
"function esc(s){if(!s)return'';const d=document.createElement('div');d.textContent=s;return d.innerHTML}\n"
"function $(id){return document.getElementById(id)}\n"
"function fmtUp(s){\n"
"  if(!s||s<=0)return'-';\n"
"  const d=Math.floor(s/86400),h=Math.floor((s%86400)/3600),m=Math.floor((s%3600)/60);\n"
"  if(d>0)return d+'d '+h+'h';if(h>0)return h+'h '+m+'m';if(m>0)return m+'m';return s+'s'\n"
"}\n"
"function fmtBytes(b){\n"
"  if(!b||b<=0)return'-';\n"
"  if(b>=1073741824)return(b/1073741824).toFixed(1)+' GiB';\n"
"  if(b>=1048576)return(b/1048576).toFixed(1)+' MiB';\n"
"  if(b>=1024)return(b/1024).toFixed(1)+' KiB';return b+' B'\n"
"}\n"
"function fmtPorts(p){\n"
"  if(!p||!p.length)return'-';\n"
"  return p.map(x=>'<span class=\"port-chip\">'+x.host+':'+x.container+'/'+x.protocol+'</span>').join('')\n"
"}\n"
"function fmtPortsText(p){\n"
"  if(!p||!p.length)return'-';\n"
"  return p.map(x=>x.host+'->'+x.container+'/'+x.protocol).join(', ')\n"
"}\n"
"function fmtTime(ts){if(!ts)return'-';return new Date(ts*1000).toLocaleString()}\n"
"function healthDot(h){\n"
"  if(!h||h==='none')return'';\n"
"  return'<span class=\"health-dot '+h+'\"></span>'+h\n"
"}\n"
"\n"
"/* TOAST */\n"
"function toast(msg,type){\n"
"  const c=$('toasts'),t=document.createElement('div');\n"
"  t.className='toast '+(type||'ok');t.textContent=msg;\n"
"  c.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));\n"
"  setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),300)},3500)\n"
"}\n"
"\n"
"/* MODAL */\n"
"function showModal(title,msg,cb){\n"
"  $('modal-title').textContent=title;$('modal-msg').textContent=msg;\n"
"  S.modalCb=cb;$('modal-overlay').classList.add('active')\n"
"}\n"
"function closeModal(){$('modal-overlay').classList.remove('active');S.modalCb=null}\n"
"function confirmModal(){if(S.modalCb)S.modalCb();closeModal()}\n"
"\n"
"/* NAVIGATION */\n"
"function navigate(page){\n"
"  S.page=page;\n"
"  document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));\n"
"  document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));\n"
"  $('pg-'+page).classList.add('active');\n"
"  const titles={dashboard:'Dashboard',containers:'Containers',images:'Images',volumes:'Volumes',networks:'Networks',build:'Build'};\n"
"  $('page-title').textContent=titles[page]||page;\n"
"  $('search-wrap').style.display=(page==='containers')?'':'none';\n"
"  clearTimers();\n"
"  if(page==='dashboard')renderDashboard();\n"
"  else if(page==='containers')renderContainers();\n"
"  else if(page==='images')refreshImages();\n"
"  else if(page==='volumes')refreshVolumes();\n"
"  else if(page==='networks')refreshNetworks();\n"
"  else if(page==='build'){}\n"
"}\n"
"\n"
"/* DATA REFRESH */\n"
"async function refresh(){\n"
"  const[sys,data]=await Promise.all([api('/api/system'),api('/api/containers')]);\n"
"  if(!sys||!data)return;\n"
"  S.system=sys;S.containers=data.containers||[];\n"
"  $('s-run').textContent=sys.containers_running;\n"
"  $('s-stop').textContent=sys.containers_stopped;\n"
"  $('sidebar-version').textContent='v'+sys.version;\n"
"  if(S.page==='dashboard')renderDashboard();\n"
"  else if(S.page==='containers')renderContainers();\n"
"}\n"
"function manualRefresh(){\n"
"  $('refresh-btn').querySelector('svg').style.animation='spin .5s';\n"
"  setTimeout(()=>$('refresh-btn').querySelector('svg').style.animation='',500);\n"
"  refresh();\n"
"  if(S.page==='images')refreshImages();\n"
"  if(S.page==='volumes')refreshVolumes();\n"
"  if(S.page==='networks')refreshNetworks();\n"
"}\n"
"function toggleAuto(){\n"
"  S.autoRefresh=!S.autoRefresh;$('auto-btn').classList.toggle('active',S.autoRefresh);\n"
"  setupAutoRefresh();toast(S.autoRefresh?'Auto-refresh enabled':'Auto-refresh paused','info')\n"
"}\n"
"function setupAutoRefresh(){\n"
"  if(S.refreshTimer)clearInterval(S.refreshTimer);\n"
"  if(S.autoRefresh)S.refreshTimer=setInterval(refresh,3000)\n"
"}\n"
"function clearTimers(){\n"
"  if(S.logTimer){clearInterval(S.logTimer);S.logTimer=null}\n"
"  if(S.statsTimer){clearInterval(S.statsTimer);S.statsTimer=null}\n"
"}\n"
"\n"
"/* MOUNTAIN SVG for empty states */\n"
"const MTN_SVG='<svg viewBox=\"0 0 120 60\" fill=\"none\"><path d=\"M0,60 L15,35 L25,42 L45,15 L60,30 L75,10 L90,28 L105,18 L120,35 L120,60Z\" fill=\"currentColor\" opacity=\".15\"/></svg>';\n"
"\n"
"/* DASHBOARD PAGE */\n"
"function renderDashboard(){\n"
"  const s=S.system;\n"
"  $('dash-stats').innerHTML=\n"
"    '<div class=\"dash-stat c-accent\"><div class=\"dash-stat-icon i-accent\"><svg viewBox=\"0 0 24 24\"><path d=\"M21 3H3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H3V5h18v14zM5 15h14v2H5v-2zm0-4h14v2H5v-2zm0-4h14v2H5V7z\"/></svg></div>'+\n"
"      '<div class=\"dash-stat-body\"><div class=\"dash-stat-num\">'+(s.containers_total||0)+'</div>'+\n"
"      '<div class=\"dash-stat-label\">Containers</div>'+\n"
"      '<div class=\"dash-stat-sub\">'+(s.containers_running||0)+' running</div></div></div>'+\n"
"    '<div class=\"dash-stat c-green\"><div class=\"dash-stat-icon i-green\"><svg viewBox=\"0 0 24 24\"><path d=\"M22 13h-8v-2h8v2zm0-6h-8v2h8V7zm-8 10h8v-2h-8v2zm-2-4V5c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v8c0 1.1.9 2 2 2h6c1.1 0 2-.9 2-2zm-1.5-1l-2.25-3-1.75 2.26-1.25-1.51L3.5 14h7z\"/></svg></div>'+\n"
"      '<div class=\"dash-stat-body\"><div class=\"dash-stat-num\">'+(s.images_total||0)+'</div>'+\n"
"      '<div class=\"dash-stat-label\">Images</div></div></div>'+\n"
"    '<div class=\"dash-stat c-orange\"><div class=\"dash-stat-icon i-orange\"><svg viewBox=\"0 0 24 24\"><path d=\"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z\"/></svg></div>'+\n"
"      '<div class=\"dash-stat-body\"><div class=\"dash-stat-num\">'+(s.networks_total||0)+'</div>'+\n"
"      '<div class=\"dash-stat-label\">Networks</div></div></div>'+\n"
"    '<div class=\"dash-stat c-purple\"><div class=\"dash-stat-icon i-purple\"><svg viewBox=\"0 0 24 24\"><path d=\"M2 20h20v-4H2v4zm2-3h2v2H4v-2zM2 4v4h20V4H2zm4 3H4V5h2v2zm-4 7h20v-4H2v4zm2-3h2v2H4v-2z\"/></svg></div>'+\n"
"      '<div class=\"dash-stat-body\"><div class=\"dash-stat-num\">'+(s.volumes_total||0)+'</div>'+\n"
"      '<div class=\"dash-stat-label\">Volumes</div></div></div>';\n"
"  const running=S.containers.filter(c=>c.state==='running');\n"
"  if(!running.length){\n"
"    $('dash-running').innerHTML='<div class=\"empty\">'+MTN_SVG+'<h3>Base camp is empty</h3><p>No running containers</p></div>';\n"
"  } else {\n"
"    $('dash-running').innerHTML=running.map(c=>\n"
"      '<div class=\"dash-run-item\" onclick=\"openDetail(\\''+esc(c.name)+'\\')\">' +\n"
"        '<div class=\"dash-run-left\">'+\n"
"          '<span class=\"status-dot running\"></span>'+\n"
"          '<div><div class=\"dash-run-name\">'+esc(c.name)+'</div>'+\n"
"            '<div class=\"dash-run-meta\"><span>'+esc(c.image)+'</span>'+\n"
"              '<span>Up '+fmtUp(c.uptime_seconds)+'</span>'+\n"
"              (c.health&&c.health!=='none'?'<span>'+healthDot(c.health)+'</span>':'')+\n"
"            '</div></div></div>'+\n"
"        '<div class=\"c-actions\" onclick=\"event.stopPropagation()\">'+\n"
"          '<button class=\"btn btn-sm btn-stop\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'stop\\')\">Stop</button>'+\n"
"          '<button class=\"btn btn-sm\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'restart\\')\">Restart</button>'+\n"
"        '</div></div>'\n"
"    ).join('');\n"
"  }\n"
"  $('dash-sysinfo').innerHTML=\n"
"    '<div class=\"sysinfo-item\"><div class=\"sysinfo-label\">Version</div><div class=\"sysinfo-val\">'+(s.version||'-')+'</div></div>'+\n"
"    '<div class=\"sysinfo-item\"><div class=\"sysinfo-label\">Storage</div><div class=\"sysinfo-val\">OverlayFS + ZFS</div></div>'+\n"
"    '<div class=\"sysinfo-item\"><div class=\"sysinfo-label\">Port</div><div class=\"sysinfo-val\">'+location.port+'</div></div>';\n"
"}\n"
"\n"
"/* CONTAINERS PAGE */\n"
"function onSearch(v){S.search=v.toLowerCase();renderContainers()}\n"
"function setFilter(f){S.stateFilter=f;renderContainers()}\n"
"function setView(v){\n"
"  S.view=v;localStorage.setItem('lochs-view',v);\n"
"  $('vt-table').classList.toggle('active',v==='table');\n"
"  $('vt-grid').classList.toggle('active',v==='grid');renderContainers()\n"
"}\n"
"function setSortBy(col){\n"
"  if(S.sortBy===col)S.sortDir=S.sortDir==='asc'?'desc':'asc';\n"
"  else{S.sortBy=col;S.sortDir='asc'}renderContainers()\n"
"}\n"
"function getFiltered(){\n"
"  let list=S.containers;\n"
"  if(S.stateFilter!=='all')list=list.filter(c=>c.state===S.stateFilter);\n"
"  if(S.search)list=list.filter(c=>(c.name||'').toLowerCase().includes(S.search)||(c.image||'').toLowerCase().includes(S.search));\n"
"  list=[...list].sort((a,b)=>{\n"
"    let va=a[S.sortBy]||'',vb=b[S.sortBy]||'';\n"
"    if(typeof va==='number')return S.sortDir==='asc'?va-vb:vb-va;\n"
"    return S.sortDir==='asc'?String(va).localeCompare(String(vb)):String(vb).localeCompare(String(va))\n"
"  });return list\n"
"}\n"
"function renderContainers(){\n"
"  const all=S.containers;\n"
"  const runC=all.filter(c=>c.state==='running').length;\n"
"  const stopC=all.filter(c=>c.state==='stopped').length;\n"
"  const createC=all.filter(c=>c.state==='created').length;\n"
"  $('filter-pills').innerHTML=\n"
"    ['all','running','stopped','created'].map(f=>{\n"
"      const cnt=f==='all'?all.length:f==='running'?runC:f==='stopped'?stopC:createC;\n"
"      return'<button class=\"filter-pill'+(S.stateFilter===f?' active':'')+'\" onclick=\"setFilter(\\''+f+'\\')\">' +\n"
"        f.charAt(0).toUpperCase()+f.slice(1)+'<span class=\"cnt\">'+cnt+'</span></button>'\n"
"    }).join('');\n"
"  const list=getFiltered(),v=$('containers-view');\n"
"  if(!list.length){\n"
"    v.innerHTML='<div class=\"empty\">'+MTN_SVG+'<h3>Your summit awaits</h3>'+\n"
"      '<p>No containers found. Create one with <code>lochs create &lt;name&gt; -i freebsd:15</code></p></div>';return\n"
"  }\n"
"  if(S.view==='table')renderContainerTable(v,list);else renderContainerGrid(v,list)\n"
"}\n"
"function sortIcon(col){\n"
"  const active=S.sortBy===col;\n"
"  return'<span class=\"sort-icon\">'+(active?(S.sortDir==='asc'?'\\u25B2':'\\u25BC'):'\\u25B4')+'</span>'\n"
"}\n"
"function renderContainerTable(el,list){\n"
"  el.innerHTML='<table class=\"c-table\"><thead><tr>'+\n"
"    '<th onclick=\"setSortBy(\\'name\\')\"'+(S.sortBy==='name'?' class=\"sorted\"':'')+'>Name'+sortIcon('name')+'</th>'+\n"
"    '<th onclick=\"setSortBy(\\'image\\')\"'+(S.sortBy==='image'?' class=\"sorted\"':'')+'>Image'+sortIcon('image')+'</th>'+\n"
"    '<th onclick=\"setSortBy(\\'state\\')\"'+(S.sortBy==='state'?' class=\"sorted\"':'')+'>State'+sortIcon('state')+'</th>'+\n"
"    '<th>IP</th><th>Ports</th><th>Health</th>'+\n"
"    '<th onclick=\"setSortBy(\\'uptime_seconds\\')\"'+(S.sortBy==='uptime_seconds'?' class=\"sorted\"':'')+'>Uptime'+sortIcon('uptime_seconds')+'</th>'+\n"
"    '<th style=\"width:130px\">Actions</th></tr></thead><tbody>'+\n"
"    list.map(c=>{\n"
"      const st=c.state||'unknown',isRun=st==='running';\n"
"      return'<tr class=\"row-'+st+'\" onclick=\"openDetail(\\''+esc(c.name)+'\\')\">' +\n"
"        '<td><strong>'+esc(c.name)+'</strong></td>'+\n"
"        '<td class=\"text-muted\">'+esc(c.image)+'</td>'+\n"
"        '<td><span class=\"badge badge-'+st+'\">'+st+'</span></td>'+\n"
"        '<td class=\"mono\">'+esc(c.ip4_addr||'-')+'</td>'+\n"
"        '<td>'+fmtPorts(c.ports)+'</td>'+\n"
"        '<td>'+healthDot(c.health)+'</td>'+\n"
"        '<td>'+fmtUp(c.uptime_seconds)+'</td>'+\n"
"        '<td onclick=\"event.stopPropagation()\"><div class=\"c-actions\">'+\n"
"          (isRun?'<button class=\"btn btn-sm btn-stop\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'stop\\')\">Stop</button>'+\n"
"                 '<button class=\"btn btn-sm\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'restart\\')\">Restart</button>'\n"
"                :'<button class=\"btn btn-sm btn-start\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'start\\')\">Start</button>'+\n"
"                 '<button class=\"btn btn-sm btn-danger\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'rm\\')\">Remove</button>')+\n"
"        '</div></td></tr>'\n"
"    }).join('')+'</tbody></table>'\n"
"}\n"
"function renderContainerGrid(el,list){\n"
"  el.innerHTML='<div class=\"card-grid\">'+list.map(c=>{\n"
"    const st=c.state||'unknown',isRun=st==='running';\n"
"    return'<div class=\"card card-'+st+'\" onclick=\"openDetail(\\''+esc(c.name)+'\\')\">' +\n"
"      '<div class=\"card-head\"><span class=\"card-name\">'+esc(c.name)+'</span>'+\n"
"        '<span class=\"badge badge-'+st+'\">'+st+'</span></div>'+\n"
"      '<div class=\"card-body\">'+\n"
"        '<div class=\"field\"><span class=\"lbl\">Image</span><span class=\"val\">'+esc(c.image)+'</span></div>'+\n"
"        '<div class=\"field\"><span class=\"lbl\">IP</span><span class=\"val\">'+(esc(c.ip4_addr)||'-')+'</span></div>'+\n"
"        '<div class=\"field\"><span class=\"lbl\">Ports</span><span class=\"val\">'+fmtPortsText(c.ports)+'</span></div>'+\n"
"        '<div class=\"field\"><span class=\"lbl\">Uptime</span><span class=\"val\">'+fmtUp(c.uptime_seconds)+'</span></div>'+\n"
"      '</div>'+\n"
"      '<div class=\"card-actions\" onclick=\"event.stopPropagation()\">'+\n"
"        (isRun?'<button class=\"btn btn-stop\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'stop\\')\">Stop</button>'+\n"
"               '<button class=\"btn\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'restart\\')\">Restart</button>'\n"
"              :'<button class=\"btn btn-start\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'start\\')\">Start</button>'+\n"
"               '<button class=\"btn btn-danger\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'rm\\')\">Remove</button>')+\n"
"      '</div></div>'\n"
"  }).join('')+'</div>'\n"
"}\n"
"\n"
"/* CONTAINER ACTIONS */\n"
"async function doAction(name,act){\n"
"  if(act==='rm'){showModal('Remove Container','Remove container \"'+name+'\"? This cannot be undone.',()=>execAction(name,act));return}\n"
"  execAction(name,act)\n"
"}\n"
"async function execAction(name,act){\n"
"  const r=await api('/api/containers/'+encodeURIComponent(name)+'/'+act,{method:'POST'});\n"
"  if(r&&r.ok)toast(act+' '+name+': success','ok');\n"
"  else toast('Error: '+(r?r.output||r.error:'request failed'),'err');\n"
"  await refresh();if(S.detail===name)loadDetailData(name)\n"
"}\n"
"\n"
"/* CREATE PANEL */\n"
"function openCreate(){\n"
"  $('cf-name').value='';$('cf-cpu').value='';$('cf-mem').value='';$('cf-pids').value='';\n"
"  $('cf-start').checked=true;$('cf-ports').innerHTML='';$('cf-envs').innerHTML='';\n"
"  loadImageSelect();\n"
"  $('create-overlay').classList.add('active');$('create-panel').classList.add('active')\n"
"}\n"
"function closeCreate(){$('create-overlay').classList.remove('active');$('create-panel').classList.remove('active')}\n"
"async function loadImageSelect(){\n"
"  const d=await api('/api/images');const sel=$('cf-image');\n"
"  sel.innerHTML='<option value=\"\">Select an image...</option>';\n"
"  if(d&&d.images){\n"
"    S.images=d.images;\n"
"    d.images.forEach(i=>{const o=document.createElement('option');\n"
"      o.value=i.repository+':'+i.tag;o.textContent=i.repository+':'+i.tag;sel.appendChild(o)})\n"
"  }\n"
"}\n"
"function addPort(){\n"
"  const div=document.createElement('div');div.className='form-row';\n"
"  div.innerHTML='<input class=\"form-input\" placeholder=\"8080\" style=\"width:80px\">'+\n"
"    '<span class=\"form-arrow\">&#8594;</span>'+\n"
"    '<input class=\"form-input\" placeholder=\"80\" style=\"width:80px\">'+\n"
"    '<span class=\"text-muted\" style=\"font-size:11px\">/tcp</span>'+\n"
"    '<button class=\"form-remove\" onclick=\"this.parentElement.remove()\">&#10005;</button>';\n"
"  $('cf-ports').appendChild(div)\n"
"}\n"
"function addEnv(){\n"
"  const div=document.createElement('div');div.className='form-row';\n"
"  div.innerHTML='<input class=\"form-input\" placeholder=\"KEY\">'+\n"
"    '<span class=\"form-arrow\">=</span>'+\n"
"    '<input class=\"form-input\" placeholder=\"value\">'+\n"
"    '<button class=\"form-remove\" onclick=\"this.parentElement.remove()\">&#10005;</button>';\n"
"  $('cf-envs').appendChild(div)\n"
"}\n"
"async function submitCreate(){\n"
"  const name=$('cf-name').value.trim(),image=$('cf-image').value;\n"
"  if(!name){toast('Container name is required','err');return}\n"
"  if(!image){toast('Please select an image','err');return}\n"
"  const body={name:name,image:image,start:$('cf-start').checked};\n"
"  const ports=[];$('cf-ports').querySelectorAll('.form-row').forEach(r=>{\n"
"    const ins=r.querySelectorAll('input');if(ins[0].value&&ins[1].value)\n"
"      ports.push(ins[0].value+':'+ins[1].value)\n"
"  });if(ports.length)body.ports=ports;\n"
"  const env={};$('cf-envs').querySelectorAll('.form-row').forEach(r=>{\n"
"    const ins=r.querySelectorAll('input');if(ins[0].value)\n"
"      env[ins[0].value]=ins[1].value||''\n"
"  });if(Object.keys(env).length)body.env=env;\n"
"  if($('cf-cpu').value)body.cpus=$('cf-cpu').value;\n"
"  if($('cf-mem').value)body.memory=$('cf-mem').value+'m';\n"
"  if($('cf-pids').value)body.pids=$('cf-pids').value;\n"
"  $('cf-submit').disabled=true;$('cf-submit').textContent='Creating...';\n"
"  const r=await api('/api/containers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});\n"
"  $('cf-submit').disabled=false;$('cf-submit').textContent='Create Container';\n"
"  if(r&&r.ok){toast('Container '+name+' created','ok');closeCreate();await refresh()}\n"
"  else toast('Error: '+(r?r.output||r.error:'failed'),'err')\n"
"}\n"
"\n"
"/* DETAIL PANEL */\n"
"async function openDetail(name){\n"
"  S.detail=name;$('d-name').textContent=name;\n"
"  $('overlay').classList.add('active');$('detail').classList.add('active');\n"
"  S.termHistory=[];showDTab('overview');loadDetailData(name)\n"
"}\n"
"function closeDetail(){\n"
"  S.detail=null;S.detailData=null;\n"
"  $('overlay').classList.remove('active');$('detail').classList.remove('active');clearTimers()\n"
"}\n"
"async function loadDetailData(name){\n"
"  const c=await api('/api/containers/'+encodeURIComponent(name));\n"
"  if(!c)return;S.detailData=c;\n"
"  $('d-status-dot').className='status-dot '+(c.state||'');\n"
"  $('d-badge').className='badge badge-'+(c.state||'');$('d-badge').textContent=c.state||'';\n"
"  renderDetailTab()\n"
"}\n"
"function showDTab(tab){\n"
"  S.detailTab=tab;\n"
"  const tabs=['overview','logs','terminal','stats','env','mounts'];\n"
"  document.querySelectorAll('.dtab').forEach((t,i)=>t.classList.toggle('active',tabs[i]===tab));\n"
"  document.querySelectorAll('.dcontent').forEach(t=>t.classList.remove('active'));\n"
"  $('d-'+tab).classList.add('active');clearTimers();renderDetailTab()\n"
"}\n"
"function renderDetailTab(){\n"
"  const c=S.detailData;if(!c)return;const tab=S.detailTab;\n"
"  if(tab==='overview')renderDetailOverview(c);\n"
"  else if(tab==='logs'){loadLogs(S.detail);S.logTimer=setInterval(()=>loadLogs(S.detail),3000)}\n"
"  else if(tab==='terminal')renderTerminal(c);\n"
"  else if(tab==='stats'){loadStats(S.detail);S.statsTimer=setInterval(()=>loadStats(S.detail),2000)}\n"
"  else if(tab==='env')renderDetailEnv(c);\n"
"  else if(tab==='mounts')renderDetailMounts(c)\n"
"}\n"
"\n"
"/* OVERVIEW TAB */\n"
"function renderDetailOverview(c){\n"
"  $('d-overview').innerHTML=\n"
"    '<div class=\"info-grid\">'+\n"
"    '<div class=\"info-item\"><div class=\"il\">State</div><div class=\"iv\"><span class=\"badge badge-'+esc(c.state)+'\">'+esc(c.state)+'</span></div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Image</div><div class=\"iv\">'+esc(c.image)+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">JID</div><div class=\"iv\">'+(c.jid||'-')+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">PID</div><div class=\"iv\">'+(c.pid||'-')+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Created</div><div class=\"iv\">'+fmtTime(c.created_at)+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Started</div><div class=\"iv\">'+fmtTime(c.started_at)+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">IP Address</div><div class=\"iv\">'+esc(c.ip4_addr||'-')+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Network</div><div class=\"iv\">'+esc(c.network||'-')+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Ports</div><div class=\"iv\">'+fmtPorts(c.ports)+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Storage</div><div class=\"iv\">'+esc(c.storage_backend||'overlay')+'</div></div>'+\n"
"    (c.cmd?'<div class=\"info-item info-full\"><div class=\"il\">Command</div><div class=\"iv mono\">'+esc(c.cmd)+'</div></div>':'')+\n"
"    (c.health&&c.health!=='none'?'<div class=\"info-item\"><div class=\"il\">Health</div><div class=\"iv\">'+healthDot(c.health)+'</div></div>':'')+\n"
"    (c.health_cmd?'<div class=\"info-item info-full\"><div class=\"il\">Health Check</div><div class=\"iv mono\">'+esc(c.health_cmd)+'</div></div>':'')+\n"
"    '</div>'+\n"
"    (c.cpus_millicores||c.memory_limit||c.pids_limit?\n"
"      '<div class=\"form-section\">Resource Limits</div><div class=\"info-grid\">'+\n"
"      (c.cpus_millicores?'<div class=\"info-item\"><div class=\"il\">CPU Limit</div><div class=\"iv\">'+(c.cpus_millicores/1000).toFixed(2)+' cores</div></div>':'')+\n"
"      (c.memory_limit?'<div class=\"info-item\"><div class=\"il\">Memory Limit</div><div class=\"iv\">'+fmtBytes(c.memory_limit)+'</div></div>':'')+\n"
"      (c.pids_limit?'<div class=\"info-item\"><div class=\"il\">PID Limit</div><div class=\"iv\">'+c.pids_limit+'</div></div>':'')+\n"
"      '</div>':'')\n"
"}\n"
"\n"
"/* LOGS TAB */\n"
"async function loadLogs(name){\n"
"  const d=await api('/api/logs/'+encodeURIComponent(name));const el=$('d-logs');\n"
"  if(!d||!d.lines||!d.lines.length){\n"
"    el.innerHTML='<div class=\"empty\">'+MTN_SVG+'<p>No logs available</p></div>';return\n"
"  }\n"
"  S.logLines=d.lines;\n"
"  renderLogView()\n"
"}\n"
"function renderLogView(){\n"
"  const el=$('d-logs');const lines=S.logLines;\n"
"  const q=S.logSearch.toLowerCase();\n"
"  const filtered=q?lines.filter(l=>l.toLowerCase().includes(q)):lines;\n"
"  el.innerHTML=\n"
"    '<div class=\"log-controls\">'+\n"
"      '<div class=\"log-controls-left\">'+\n"
"        '<input class=\"log-search\" placeholder=\"Search logs...\" value=\"'+esc(S.logSearch)+'\" oninput=\"S.logSearch=this.value;renderLogView()\">'+\n"
"        '<span class=\"log-badge\">'+filtered.length+' / '+lines.length+' lines</span>'+\n"
"      '</div>'+\n"
"      '<div><button class=\"btn btn-sm\" onclick=\"downloadLogs()\">Download</button></div>'+\n"
"    '</div>'+\n"
"    '<div class=\"log-viewer\" id=\"log-box\">'+\n"
"      filtered.map((l,i)=>{\n"
"        let cls='';\n"
"        const ll=l.toLowerCase();\n"
"        if(ll.includes('error')||ll.includes('fatal')||ll.includes('panic'))cls=' log-error';\n"
"        else if(ll.includes('warn'))cls=' log-warn';\n"
"        else if(ll.includes('info'))cls=' log-info';\n"
"        return'<div class=\"log-line\"><span class=\"log-num\">'+(i+1)+'</span><span class=\"log-text'+cls+'\">'+esc(l)+'</span></div>'\n"
"      }).join('')+\n"
"    '</div>';\n"
"  const box=$('log-box');if(box)box.scrollTop=box.scrollHeight\n"
"}\n"
"function downloadLogs(){\n"
"  if(!S.detail)return;\n"
"  window.open('/api/logs/'+encodeURIComponent(S.detail)+'/download','_blank')\n"
"}\n"
"\n"
"/* TERMINAL TAB */\n"
"function renderTerminal(c){\n"
"  const el=$('d-terminal');\n"
"  if(c.state!=='running'){\n"
"    el.innerHTML='<div class=\"term-disabled\">Terminal is only available for running containers.</div>';return\n"
"  }\n"
"  el.innerHTML='<div class=\"term-wrap\">'+\n"
"    '<div class=\"term-output\" id=\"term-out\">'+\n"
"      S.termHistory.map(h=>'<div class=\"term-cmd\">$ '+esc(h.cmd)+'</div><div>'+esc(h.out)+'</div>').join('')+\n"
"      (S.termHistory.length?'':'<div style=\"color:var(--text3)\">Type a command below to execute in the container.</div>')+\n"
"    '</div>'+\n"
"    '<div class=\"term-input-row\">'+\n"
"      '<span class=\"term-prompt\">$</span>'+\n"
"      '<input class=\"term-input\" id=\"term-cmd\" placeholder=\"Enter command...\" onkeydown=\"if(event.key===\\'Enter\\')runExec()\">'+\n"
"      '<button class=\"btn btn-primary\" onclick=\"runExec()\">Run</button>'+\n"
"    '</div></div>';\n"
"  const out=$('term-out');if(out)out.scrollTop=out.scrollHeight\n"
"}\n"
"async function runExec(){\n"
"  const input=$('term-cmd');if(!input)return;\n"
"  const cmd=input.value.trim();if(!cmd)return;input.value='';\n"
"  const out=$('term-out');if(out)out.innerHTML+='<div class=\"term-cmd\">$ '+esc(cmd)+'</div><div><span class=\"spinner\"></span> Running...</div>';\n"
"  if(out)out.scrollTop=out.scrollHeight;\n"
"  const r=await api('/api/containers/'+encodeURIComponent(S.detail)+'/exec',{\n"
"    method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cmd:cmd})\n"
"  });\n"
"  const output=r?(r.output||r.error||'(no output)'):'Request failed';\n"
"  S.termHistory.push({cmd:cmd,out:output});\n"
"  if(out){out.lastElementChild.innerHTML=esc(output);out.scrollTop=out.scrollHeight}\n"
"}\n"
"\n"
"/* STATS TAB */\n"
"async function loadStats(name){\n"
"  const d=await api('/api/stats/'+encodeURIComponent(name));const el=$('d-stats');\n"
"  if(!d){el.innerHTML='<div class=\"empty\">'+MTN_SVG+'<p>No stats available</p></div>';return}\n"
"  const memPct=d.memory_limit_bytes>0?Math.min(100,Math.round(d.memory_bytes/d.memory_limit_bytes*100)):0;\n"
"  const pidPct=d.pids_limit>0?Math.min(100,Math.round(d.pids/d.pids_limit*100)):0;\n"
"  function ring(pct,label,val,sub){\n"
"    const r=38,circ=2*Math.PI*r,off=circ*(1-pct/100);\n"
"    const c=pct>90?'var(--unhealthy)':pct>70?'var(--starting)':'var(--running)';\n"
"    return'<div class=\"stat-card\"><div class=\"stat-label\">'+label+'</div>'+\n"
"      (pct>0?'<div class=\"stat-ring\"><svg width=\"90\" height=\"90\" viewBox=\"0 0 90 90\">'+\n"
"        '<circle cx=\"45\" cy=\"45\" r=\"'+r+'\" fill=\"none\" stroke=\"var(--border)\" stroke-width=\"5\"/>'+\n"
"        '<circle cx=\"45\" cy=\"45\" r=\"'+r+'\" fill=\"none\" stroke=\"'+c+'\" stroke-width=\"5\"'+\n"
"        ' stroke-dasharray=\"'+circ+'\" stroke-dashoffset=\"'+off+'\" stroke-linecap=\"round\"/>'+\n"
"      '</svg><div class=\"stat-ring-text\">'+pct+'%</div></div>':'<div class=\"stat-value\">'+val+'</div>')+\n"
"      '<div class=\"stat-sub\">'+sub+'</div></div>'\n"
"  }\n"
"  el.innerHTML='<div class=\"stats-grid\">'+\n"
"    '<div class=\"stat-card\"><div class=\"stat-label\">CPU Time</div>'+\n"
"      '<div class=\"stat-value\">'+(d.cpu_usage_usec/1000000).toFixed(2)+'s</div>'+\n"
"      '<div class=\"stat-sub\">Total CPU time used</div></div>'+\n"
"    ring(memPct,'Memory',fmtBytes(d.memory_bytes),fmtBytes(d.memory_bytes)+' / '+(d.memory_limit_bytes>0?fmtBytes(d.memory_limit_bytes):'unlimited'))+\n"
"    ring(pidPct,'Processes',d.pids||0,(d.pids||0)+' / '+(d.pids_limit>0?d.pids_limit:'unlimited'))+\n"
"    '<div class=\"stat-card\"><div class=\"stat-label\">Swap</div>'+\n"
"      '<div class=\"stat-value\">'+fmtBytes(d.swap_bytes)+'</div>'+\n"
"      '<div class=\"stat-sub\">Swap memory used</div></div></div>'+\n"
"    '<div style=\"margin-top:16px\"><div class=\"section-title\">Resource History</div>'+\n"
"      '<div style=\"display:grid;grid-template-columns:1fr 1fr;gap:14px\">'+\n"
"        '<div class=\"stat-card\"><div class=\"stat-label\">CPU Usage Over Time</div>'+\n"
"          '<canvas id=\"chart-cpu\" width=\"320\" height=\"140\" style=\"width:100%;height:140px\"></canvas></div>'+\n"
"        '<div class=\"stat-card\"><div class=\"stat-label\">Memory Usage Over Time</div>'+\n"
"          '<canvas id=\"chart-mem\" width=\"320\" height=\"140\" style=\"width:100%;height:140px\"></canvas></div>'+\n"
"      '</div></div>';\n"
"  loadStatsHistory(name)\n"
"}\n"
"\n"
"/* ENV TAB */\n"
"function renderDetailEnv(c){\n"
"  const el=$('d-env');\n"
"  if(!c.env||!c.env.length){el.innerHTML='<div class=\"empty\"><p>No environment variables</p></div>';return}\n"
"  el.innerHTML='<table class=\"env-table\"><thead><tr><th>Key</th><th>Value</th></tr></thead><tbody>'+\n"
"    c.env.map(e=>'<tr><td>'+esc(e.key)+'</td><td>'+esc(e.value)+'</td></tr>').join('')+'</tbody></table>'\n"
"}\n"
"\n"
"/* MOUNTS TAB */\n"
"function renderDetailMounts(c){\n"
"  const el=$('d-mounts');\n"
"  if(!c.volumes||!c.volumes.length){el.innerHTML='<div class=\"empty\"><p>No mounts configured</p></div>';return}\n"
"  el.innerHTML='<table class=\"mount-table\"><thead><tr><th>Host Path</th><th>Container Path</th><th>Mode</th></tr></thead><tbody>'+\n"
"    c.volumes.map(v=>'<tr><td>'+esc(v.host)+'</td><td>'+esc(v.container)+'</td>'+\n"
"      '<td>'+(v.readonly?'<span class=\"ro-badge\">RO</span>':'<span class=\"rw-badge\">RW</span>')+'</td></tr>'\n"
"    ).join('')+'</tbody></table>'\n"
"}\n"
"\n"
"/* IMAGES PAGE */\n"
"async function refreshImages(){\n"
"  const d=await api('/api/images');const el=$('images-view');\n"
"  if(!d||!d.images||!d.images.length){\n"
"    el.innerHTML='<div class=\"empty\">'+MTN_SVG+'<h3>No images</h3><p>Pull one with <code>lochs pull freebsd:15</code></p></div>';return\n"
"  }\n"
"  el.innerHTML='<table class=\"data-table\"><thead><tr><th>Repository</th><th>Tag</th><th>ID</th><th>Size</th><th>Pulled</th><th>Actions</th></tr></thead><tbody>'+\n"
"    d.images.map(i=>'<tr><td><strong>'+esc(i.repository)+'</strong></td>'+\n"
"      '<td><span class=\"badge badge-created\">'+esc(i.tag)+'</span></td>'+\n"
"      '<td class=\"mono text-muted\">'+esc((i.id||'').substring(0,12))+'</td>'+\n"
"      '<td>'+fmtBytes(i.size)+'</td>'+\n"
"      '<td class=\"text-muted\">'+fmtTime(i.pulled)+'</td>'+\n"
"      '<td><button class=\"btn btn-sm btn-danger\" onclick=\"deleteImage(\\''+esc(i.repository)+':'+esc(i.tag)+'\\')\">' +\n"
"        'Delete</button></td></tr>'\n"
"    ).join('')+'</tbody></table>'\n"
"}\n"
"function deleteImage(spec){\n"
"  showModal('Delete Image','Delete image \"'+spec+'\"? This cannot be undone.',async()=>{\n"
"    const r=await api('/api/images/'+encodeURIComponent(spec),{method:'DELETE'});\n"
"    if(r&&r.ok)toast('Deleted '+spec,'ok');else toast('Error: '+(r?r.output||r.error:'failed'),'err');\n"
"    refreshImages()\n"
"  })\n"
"}\n"
"\n"
"/* PULL MODAL */\n"
"function openPull(){$('pull-input').value='';$('pull-status').classList.remove('active');\n"
"  $('pull-btn').disabled=false;$('pull-overlay').classList.add('active')}\n"
"function closePull(){$('pull-overlay').classList.remove('active')}\n"
"async function submitPull(){\n"
"  const img=$('pull-input').value.trim();if(!img){toast('Enter an image name','err');return}\n"
"  $('pull-btn').disabled=true;$('pull-status').classList.add('active');\n"
"  $('pull-status-text').textContent='Pulling '+img+'...';\n"
"  const r=await api('/api/images/pull',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:img})});\n"
"  $('pull-btn').disabled=false;$('pull-status').classList.remove('active');\n"
"  if(r&&r.ok){toast('Pulled '+img+' successfully','ok');closePull();refreshImages()}\n"
"  else toast('Error: '+(r?r.output||r.error:'pull failed'),'err')\n"
"}\n"
"\n"
"/* VOLUMES PAGE */\n"
"async function refreshVolumes(){\n"
"  const d=await api('/api/volumes');const el=$('volumes-view');\n"
"  if(!d||!d.volumes||!d.volumes.length){\n"
"    el.innerHTML='<div class=\"empty\">'+MTN_SVG+'<h3>No volumes</h3><p>Click <strong>+ Create Volume</strong> or use <code>lochs volume create &lt;name&gt;</code></p></div>';return\n"
"  }\n"
"  el.innerHTML='<table class=\"data-table\"><thead><tr><th>Name</th><th>Path</th><th>ZFS Dataset</th><th>Created</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+\n"
"    d.volumes.map(v=>'<tr><td><strong>'+esc(v.name)+'</strong></td>'+\n"
"      '<td class=\"mono text-muted\">'+esc(v.path||'-')+'</td>'+\n"
"      '<td class=\"mono text-muted\">'+esc(v.zfs_dataset||'-')+'</td>'+\n"
"      '<td class=\"text-muted\">'+fmtTime(v.created_at)+'</td>'+\n"
"      '<td><span class=\"badge '+(v.active?'badge-active':'badge-inactive')+'\">'+(v.active?'active':'inactive')+'</span></td>'+\n"
"      '<td><button class=\"btn btn-sm btn-danger\" onclick=\"deleteVolume(\\''+esc(v.name)+'\\')\">' +\n"
"        'Delete</button></td></tr>'\n"
"    ).join('')+'</tbody></table>'\n"
"}\n"
"\n"
"/* NETWORKS PAGE */\n"
"async function refreshNetworks(){\n"
"  const d=await api('/api/networks');const el=$('networks-view');\n"
"  if(!d||!d.networks||!d.networks.length){\n"
"    el.innerHTML='<div class=\"empty\">'+MTN_SVG+'<h3>No networks</h3><p>Click <strong>+ Create Network</strong> or use <code>lochs network create &lt;name&gt;</code></p></div>';return\n"
"  }\n"
"  const nc={};S.containers.forEach(c=>{if(c.network){nc[c.network]=(nc[c.network]||0)+1}});\n"
"  el.innerHTML='<table class=\"data-table\"><thead><tr><th>Name</th><th>Subnet</th><th>Gateway</th><th>Bridge</th><th>Containers</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+\n"
"    d.networks.map(n=>'<tr><td><strong>'+esc(n.name)+'</strong></td>'+\n"
"      '<td class=\"mono\">'+esc(n.subnet)+'</td>'+\n"
"      '<td class=\"mono\">'+esc(n.gateway)+'</td>'+\n"
"      '<td class=\"mono text-muted\">'+esc(n.bridge)+'</td>'+\n"
"      '<td>'+(nc[n.name]||0)+'</td>'+\n"
"      '<td><span class=\"badge '+(n.active?'badge-active':'badge-inactive')+'\">'+(n.active?'active':'inactive')+'</span></td>'+\n"
"      '<td><button class=\"btn btn-sm btn-danger\" onclick=\"deleteNetwork(\\''+esc(n.name)+'\\')\">' +\n"
"        'Delete</button></td></tr>'\n"
"    ).join('')+'</tbody></table>'\n"
"}\n"
"\n"
"/* NETWORK CRUD */\n"
"function openNetCreate(){\n"
"  showModal('Create Network','',null);\n"
"  $('modal-title').textContent='Create Network';\n"
"  $('modal-msg').innerHTML='<div class=\"form-group\"><label class=\"form-label\">Network Name</label>'+\n"
"    '<input class=\"form-input\" id=\"net-name\" placeholder=\"mynet\"></div>'+\n"
"    '<div class=\"form-group\"><label class=\"form-label\">Subnet (optional)</label>'+\n"
"    '<input class=\"form-input\" id=\"net-subnet\" placeholder=\"172.20.0.0/16\"></div>';\n"
"  S.modalCb=async()=>{\n"
"    const n=$('net-name').value.trim();if(!n){toast('Name required','err');return}\n"
"    const body={name:n};const sub=$('net-subnet')?$('net-subnet').value.trim():'';\n"
"    if(sub)body.subnet=sub;\n"
"    const r=await api('/api/networks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});\n"
"    if(r&&r.ok)toast('Network '+n+' created','ok');else toast('Error: '+(r?r.output||r.error:'failed'),'err');\n"
"    refreshNetworks()\n"
"  }\n"
"}\n"
"function deleteNetwork(name){\n"
"  showModal('Delete Network','Delete network \"'+name+'\"?',async()=>{\n"
"    const r=await api('/api/networks/'+encodeURIComponent(name),{method:'DELETE'});\n"
"    if(r&&r.ok)toast('Deleted '+name,'ok');else toast('Error: '+(r?r.output||r.error:'failed'),'err');\n"
"    refreshNetworks()\n"
"  })\n"
"}\n"
"\n"
"/* VOLUME CRUD */\n"
"function openVolCreate(){\n"
"  showModal('Create Volume','',null);\n"
"  $('modal-title').textContent='Create Volume';\n"
"  $('modal-msg').innerHTML='<div class=\"form-group\"><label class=\"form-label\">Volume Name</label>'+\n"
"    '<input class=\"form-input\" id=\"vol-name\" placeholder=\"mydata\"></div>';\n"
"  S.modalCb=async()=>{\n"
"    const n=$('vol-name').value.trim();if(!n){toast('Name required','err');return}\n"
"    const r=await api('/api/volumes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n})});\n"
"    if(r&&r.ok)toast('Volume '+n+' created','ok');else toast('Error: '+(r?r.output||r.error:'failed'),'err');\n"
"    refreshVolumes()\n"
"  }\n"
"}\n"
"function deleteVolume(name){\n"
"  showModal('Delete Volume','Delete volume \"'+name+'\"? Data will be lost.',async()=>{\n"
"    const r=await api('/api/volumes/'+encodeURIComponent(name),{method:'DELETE'});\n"
"    if(r&&r.ok)toast('Deleted '+name,'ok');else toast('Error: '+(r?r.output||r.error:'failed'),'err');\n"
"    refreshVolumes()\n"
"  })\n"
"}\n"
"\n"
"/* STATS HISTORY CHART */\n"
"async function loadStatsHistory(name){\n"
"  const d=await api('/api/stats/'+encodeURIComponent(name)+'/history');\n"
"  if(!d||!d.points||d.points.length<2)return;\n"
"  drawChart('chart-cpu',d.points.map(p=>p.cpu/1000000),'CPU (s)','#3d7dd8');\n"
"  drawChart('chart-mem',d.points.map(p=>p.mem),'Memory','#34d399')\n"
"}\n"
"function drawChart(id,data,label,color){\n"
"  const c=$(id);if(!c)return;const ctx=c.getContext('2d');\n"
"  const W=c.width,H=c.height;ctx.clearRect(0,0,W,H);\n"
"  if(data.length<2)return;\n"
"  const max=Math.max(...data)*1.1||1,min=Math.min(...data)*0.9||0;\n"
"  const range=max-min||1;\n"
"  ctx.strokeStyle='var(--border)';ctx.lineWidth=0.5;\n"
"  for(let i=0;i<4;i++){const y=H*i/3;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}\n"
"  ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();\n"
"  data.forEach((v,i)=>{\n"
"    const x=W*i/(data.length-1),y=H-(v-min)/range*H;\n"
"    if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)\n"
"  });ctx.stroke();\n"
"  ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.closePath();\n"
"  ctx.fillStyle=color.replace(')',',0.08)').replace('rgb','rgba');ctx.fill()\n"
"}\n"
"\n"
"/* BUILD PAGE */\n"
"function loadTemplate(){\n"
"  const t=$('bf-template').value,e=$('bf-editor');\n"
"  if(t==='basic')e.value='FROM freebsd:15\\n\\nRUN pkg update -f\\nRUN pkg install -y curl wget\\n\\nCMD /bin/sh';\n"
"  else if(t==='nginx')e.value='FROM freebsd:15\\n\\nRUN pkg install -y nginx\\nRUN echo \\\"server { listen 80; root /usr/local/www; }\\\" > /usr/local/etc/nginx/nginx.conf\\n\\nEXPOSE 80\\nCMD nginx -g \\\"daemon off;\\\"';\n"
"  else if(t==='node')e.value='FROM freebsd:15\\n\\nRUN pkg install -y node npm\\nCOPY . /app\\nWORKDIR /app\\nRUN npm install\\n\\nEXPOSE 3000\\nCMD node server.js'\n"
"}\n"
"async function submitBuild(){\n"
"  const content=$('bf-editor').value.trim();if(!content){toast('Write a Lochfile first','err');return}\n"
"  const tag=$('bf-tag').value.trim();\n"
"  const out=$('build-output');out.style.display='block';out.textContent='Building...\\n';\n"
"  const r=await api('/api/build',{method:'POST',headers:{'Content-Type':'application/json'},\n"
"    body:JSON.stringify({content:content,tag:tag})});\n"
"  if(r&&r.ok){out.textContent+=(r.output||'Build succeeded!');toast('Build complete','ok')}\n"
"  else{out.textContent+=(r?r.output||r.error:'Build failed');toast('Build failed','err')}\n"
"}\n"
"\n"
"/* SIDEBAR */\n"
"function toggleSidebar(){$('sidebar').classList.toggle('collapsed')}\n"
"\n"
"/* INIT */\n"
"$('auto-btn').classList.add('active');\n"
"refresh();setupAutoRefresh();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* LOCHS_DASHBOARD_HTML_H */
