/*
 * Lochs Dashboard - Embedded HTML/CSS/JS
 *
 * Single-page dark-themed web UI for container management.
 * This entire file is a static const char[] compiled into the binary.
 */

#ifndef LOCHS_DASHBOARD_HTML_H
#define LOCHS_DASHBOARD_HTML_H

static const char DASHBOARD_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
"<title>Lochs Dashboard</title>\n"
"<style>\n"
"*{margin:0;padding:0;box-sizing:border-box}\n"
":root{\n"
"  --bg:#0d1117;--card:#161b22;--border:#30363d;--border-hover:#c9372c;\n"
"  --text:#e6edf3;--text2:#8b949e;--accent:#c9372c;--accent2:#ff6b6b;\n"
"  --running:#3fb950;--stopped:#8b949e;--created:#58a6ff;\n"
"  --healthy:#3fb950;--unhealthy:#f85149;--starting:#d29922;\n"
"  --radius:8px;--shadow:0 1px 3px rgba(0,0,0,.4)\n"
"}\n"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;\n"
"  background:var(--bg);color:var(--text);min-height:100vh}\n"
"a{color:var(--accent2);text-decoration:none}\n"
"\n"
"/* Header */\n"
".header{background:var(--card);border-bottom:1px solid var(--border);\n"
"  padding:14px 24px;display:flex;align-items:center;justify-content:space-between;\n"
"  position:sticky;top:0;z-index:100}\n"
".logo{font-size:20px;font-weight:700;color:var(--accent)}\n"
".logo span{color:var(--text2);font-weight:400;font-size:13px;margin-left:8px}\n"
".header-stats{display:flex;gap:12px}\n"
".pill{background:var(--bg);border:1px solid var(--border);border-radius:20px;\n"
"  padding:4px 14px;font-size:13px;display:flex;align-items:center;gap:6px}\n"
".pill .dot{width:8px;height:8px;border-radius:50%;display:inline-block}\n"
".pill .dot.green{background:var(--running)}\n"
".pill .dot.gray{background:var(--stopped)}\n"
".pill .dot.blue{background:var(--created)}\n"
"\n"
"/* Tabs */\n"
".tabs{display:flex;gap:0;padding:0 24px;background:var(--card);\n"
"  border-bottom:1px solid var(--border)}\n"
".tab{background:none;border:none;color:var(--text2);padding:12px 20px;\n"
"  font-size:14px;cursor:pointer;border-bottom:2px solid transparent;\n"
"  transition:all .2s}\n"
".tab:hover{color:var(--text)}\n"
".tab.active{color:var(--text);border-bottom-color:var(--accent)}\n"
"\n"
"/* Main content */\n"
".main{padding:20px 24px;max-width:1400px;margin:0 auto}\n"
".tab-content{display:none}\n"
".tab-content.active{display:block}\n"
"\n"
"/* Card grid */\n"
".card-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:16px}\n"
".card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);\n"
"  padding:20px;transition:border-color .2s,box-shadow .2s;cursor:pointer}\n"
".card:hover{border-color:var(--border-hover);box-shadow:var(--shadow)}\n"
".card-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}\n"
".card-name{font-size:16px;font-weight:600}\n"
".badge{padding:3px 10px;border-radius:12px;font-size:11px;font-weight:600;\n"
"  text-transform:uppercase;letter-spacing:.5px}\n"
".badge-running{background:rgba(63,185,80,.15);color:var(--running)}\n"
".badge-stopped{background:rgba(139,148,158,.15);color:var(--stopped)}\n"
".badge-created{background:rgba(88,166,255,.15);color:var(--created)}\n"
".badge-removed{background:rgba(248,81,73,.15);color:var(--unhealthy)}\n"
"\n"
"/* Card fields */\n"
".card-body{display:grid;grid-template-columns:1fr 1fr;gap:6px 16px;font-size:13px;\n"
"  margin-bottom:14px}\n"
".field{display:flex;gap:6px}\n"
".field .lbl{color:var(--text2);min-width:55px}\n"
".field .val{color:var(--text);word-break:break-all}\n"
".health-dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:4px}\n"
".health-dot.healthy{background:var(--healthy);box-shadow:0 0 6px var(--healthy)}\n"
".health-dot.unhealthy{background:var(--unhealthy);box-shadow:0 0 6px var(--unhealthy)}\n"
".health-dot.starting{background:var(--starting);box-shadow:0 0 6px var(--starting)}\n"
"\n"
"/* Card actions */\n"
".card-actions{display:flex;gap:8px;border-top:1px solid var(--border);padding-top:12px}\n"
".btn{background:var(--bg);border:1px solid var(--border);color:var(--text);\n"
"  padding:6px 14px;border-radius:6px;font-size:12px;cursor:pointer;\n"
"  transition:all .15s;font-weight:500}\n"
".btn:hover{border-color:var(--text2)}\n"
".btn-start{border-color:rgba(63,185,80,.4);color:var(--running)}\n"
".btn-start:hover{background:rgba(63,185,80,.1);border-color:var(--running)}\n"
".btn-stop{border-color:rgba(248,81,73,.4);color:var(--unhealthy)}\n"
".btn-stop:hover{background:rgba(248,81,73,.1);border-color:var(--unhealthy)}\n"
".btn-danger{background:rgba(218,54,51,.1);border-color:rgba(218,54,51,.4);color:#f85149}\n"
".btn-danger:hover{background:rgba(218,54,51,.2);border-color:#da3633}\n"
".btn:disabled{opacity:.5;cursor:not-allowed}\n"
"\n"
"/* Detail panel */\n"
".detail-overlay{display:none;position:fixed;top:0;left:0;right:0;bottom:0;\n"
"  background:rgba(0,0,0,.6);z-index:200}\n"
".detail-overlay.active{display:block}\n"
".detail-panel{position:fixed;top:0;right:0;bottom:0;width:680px;max-width:100vw;\n"
"  background:var(--card);border-left:1px solid var(--border);z-index:201;\n"
"  display:flex;flex-direction:column;transform:translateX(100%);\n"
"  transition:transform .25s ease}\n"
".detail-panel.active{transform:translateX(0)}\n"
".detail-head{display:flex;align-items:center;justify-content:space-between;\n"
"  padding:16px 20px;border-bottom:1px solid var(--border)}\n"
".detail-head h2{font-size:18px}\n"
".close-btn{background:none;border:1px solid var(--border);color:var(--text2);\n"
"  width:32px;height:32px;border-radius:6px;cursor:pointer;font-size:16px;\n"
"  display:flex;align-items:center;justify-content:center}\n"
".close-btn:hover{border-color:var(--text);color:var(--text)}\n"
"\n"
"/* Detail tabs */\n"
".detail-tabs{display:flex;gap:0;border-bottom:1px solid var(--border)}\n"
".dtab{background:none;border:none;color:var(--text2);padding:10px 18px;\n"
"  font-size:13px;cursor:pointer;border-bottom:2px solid transparent}\n"
".dtab.active{color:var(--text);border-bottom-color:var(--accent)}\n"
".detail-body{flex:1;overflow-y:auto;padding:20px}\n"
".dcontent{display:none}\n"
".dcontent.active{display:block}\n"
"\n"
"/* Info section */\n"
".info-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}\n"
".info-item{background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:12px}\n"
".info-item .il{color:var(--text2);font-size:11px;text-transform:uppercase;\n"
"  letter-spacing:.5px;margin-bottom:4px}\n"
".info-item .iv{font-size:14px}\n"
".info-full{grid-column:1/-1}\n"
"\n"
"/* Log viewer */\n"
".log-viewer{background:#010409;border:1px solid var(--border);border-radius:6px;\n"
"  padding:14px;font-family:'SF Mono',Consolas,'Liberation Mono',Menlo,monospace;\n"
"  font-size:12px;line-height:1.6;color:#8b949e;max-height:500px;overflow-y:auto;\n"
"  white-space:pre-wrap;word-break:break-all}\n"
".log-viewer::-webkit-scrollbar{width:6px}\n"
".log-viewer::-webkit-scrollbar-track{background:#010409}\n"
".log-viewer::-webkit-scrollbar-thumb{background:var(--border);border-radius:3px}\n"
"\n"
"/* Stats */\n"
".stats-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}\n"
".stat-card{background:var(--bg);border:1px solid var(--border);border-radius:6px;\n"
"  padding:16px;text-align:center}\n"
".stat-label{color:var(--text2);font-size:11px;text-transform:uppercase;\n"
"  letter-spacing:.5px;margin-bottom:8px}\n"
".stat-value{font-size:24px;font-weight:700}\n"
".stat-sub{color:var(--text2);font-size:12px;margin-top:4px}\n"
".stat-bar{height:6px;background:var(--border);border-radius:3px;margin-top:8px;overflow:hidden}\n"
".stat-bar-fill{height:100%;border-radius:3px;transition:width .5s}\n"
".stat-bar-fill.green{background:var(--running)}\n"
".stat-bar-fill.yellow{background:var(--starting)}\n"
".stat-bar-fill.red{background:var(--unhealthy)}\n"
"\n"
"/* Image & network cards */\n"
".list-card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);\n"
"  padding:16px;display:flex;align-items:center;justify-content:space-between}\n"
".list-grid{display:flex;flex-direction:column;gap:10px}\n"
".list-info{display:flex;gap:20px;font-size:13px}\n"
".list-info span{color:var(--text2)}\n"
".list-name{font-weight:600;font-size:15px;margin-bottom:4px}\n"
"\n"
"/* Toast */\n"
".toast{position:fixed;bottom:24px;right:24px;padding:12px 20px;border-radius:8px;\n"
"  font-size:14px;z-index:300;transform:translateY(100px);opacity:0;\n"
"  transition:all .3s ease}\n"
".toast.show{transform:translateY(0);opacity:1}\n"
".toast.ok{background:#238636;color:#fff}\n"
".toast.err{background:#da3633;color:#fff}\n"
"\n"
"/* Empty state */\n"
".empty{text-align:center;padding:60px 20px;color:var(--text2)}\n"
".empty h3{font-size:18px;margin-bottom:8px;color:var(--text)}\n"
".empty p{font-size:14px}\n"
"\n"
"/* Spinner */\n"
"@keyframes spin{to{transform:rotate(360deg)}}\n"
".spinner{width:20px;height:20px;border:2px solid var(--border);border-top-color:var(--accent);\n"
"  border-radius:50%;animation:spin .6s linear infinite;display:inline-block}\n"
"\n"
"/* Responsive */\n"
"@media(max-width:768px){\n"
"  .card-grid{grid-template-columns:1fr}\n"
"  .detail-panel{width:100vw}\n"
"  .header{flex-direction:column;gap:10px}\n"
"  .info-grid,.stats-grid{grid-template-columns:1fr}\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<div class=\"header\">\n"
"  <div>\n"
"    <span class=\"logo\">&#127956; Lochs.dev<span>FreeBSD jails on Linux</span></span>\n"
"  </div>\n"
"  <div class=\"header-stats\">\n"
"    <div class=\"pill\"><span class=\"dot green\"></span><span id=\"s-run\">0</span> running</div>\n"
"    <div class=\"pill\"><span class=\"dot gray\"></span><span id=\"s-stop\">0</span> stopped</div>\n"
"    <div class=\"pill\"><span class=\"dot blue\"></span><span id=\"s-img\">0</span> images</div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"tabs\">\n"
"  <button class=\"tab active\" onclick=\"showTab('containers')\">Containers</button>\n"
"  <button class=\"tab\" onclick=\"showTab('images')\">Images</button>\n"
"  <button class=\"tab\" onclick=\"showTab('networks')\">Networks</button>\n"
"</div>\n"
"\n"
"<div class=\"main\">\n"
"  <div id=\"t-containers\" class=\"tab-content active\">\n"
"    <div id=\"containers-grid\" class=\"card-grid\"></div>\n"
"  </div>\n"
"  <div id=\"t-images\" class=\"tab-content\">\n"
"    <div id=\"images-grid\" class=\"list-grid\"></div>\n"
"  </div>\n"
"  <div id=\"t-networks\" class=\"tab-content\">\n"
"    <div id=\"networks-grid\" class=\"list-grid\"></div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<!-- Detail panel -->\n"
"<div id=\"overlay\" class=\"detail-overlay\" onclick=\"closeDetail()\"></div>\n"
"<div id=\"detail\" class=\"detail-panel\">\n"
"  <div class=\"detail-head\">\n"
"    <h2 id=\"d-name\"></h2>\n"
"    <button class=\"close-btn\" onclick=\"closeDetail()\">&#10005;</button>\n"
"  </div>\n"
"  <div class=\"detail-tabs\">\n"
"    <button class=\"dtab active\" onclick=\"showDTab('info')\">Info</button>\n"
"    <button class=\"dtab\" onclick=\"showDTab('logs')\">Logs</button>\n"
"    <button class=\"dtab\" onclick=\"showDTab('stats')\">Stats</button>\n"
"  </div>\n"
"  <div class=\"detail-body\">\n"
"    <div id=\"d-info\" class=\"dcontent active\"></div>\n"
"    <div id=\"d-logs\" class=\"dcontent\"></div>\n"
"    <div id=\"d-stats\" class=\"dcontent\"></div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div id=\"toast\" class=\"toast\"></div>\n"
"\n"
"<script>\n"
"let currentDetail=null,logInterval=null;\n"
"\n"
"async function api(path,opts){try{const r=await fetch(path,opts);return await r.json()}catch(e){return null}}\n"
"\n"
"function esc(s){if(!s)return'';const d=document.createElement('div');d.textContent=s;return d.innerHTML}\n"
"\n"
"function fmtUp(s){\n"
"  if(!s||s<=0)return'-';\n"
"  const d=Math.floor(s/86400),h=Math.floor((s%86400)/3600),m=Math.floor((s%3600)/60);\n"
"  if(d>0)return d+'d '+h+'h';\n"
"  if(h>0)return h+'h '+m+'m';\n"
"  if(m>0)return m+'m';\n"
"  return s+'s'\n"
"}\n"
"\n"
"function fmtBytes(b){\n"
"  if(!b||b<=0)return'-';\n"
"  if(b>=1073741824)return(b/1073741824).toFixed(1)+' GiB';\n"
"  if(b>=1048576)return(b/1048576).toFixed(1)+' MiB';\n"
"  if(b>=1024)return(b/1024).toFixed(1)+' KiB';\n"
"  return b+' B'\n"
"}\n"
"\n"
"function fmtPorts(ports){\n"
"  if(!ports||!ports.length)return'-';\n"
"  return ports.map(p=>p.host+'->'+p.container+'/'+p.protocol).join(', ')\n"
"}\n"
"\n"
"function fmtTime(ts){\n"
"  if(!ts)return'-';\n"
"  return new Date(ts*1000).toLocaleString()\n"
"}\n"
"\n"
"function healthDot(h){\n"
"  if(!h||h==='none')return'';\n"
"  return'<span class=\"health-dot '+esc(h)+'\"></span>'+esc(h)\n"
"}\n"
"\n"
"function toast(msg,ok){\n"
"  const t=document.getElementById('toast');\n"
"  t.textContent=msg;t.className='toast show '+(ok?'ok':'err');\n"
"  setTimeout(()=>t.className='toast',3000)\n"
"}\n"
"\n"
"/* === Containers === */\n"
"async function refresh(){\n"
"  const[sys,data]=await Promise.all([api('/api/system'),api('/api/containers')]);\n"
"  if(!sys||!data)return;\n"
"  document.getElementById('s-run').textContent=sys.containers_running;\n"
"  document.getElementById('s-stop').textContent=sys.containers_stopped;\n"
"  document.getElementById('s-img').textContent=sys.images_total;\n"
"  renderContainers(data.containers||[])\n"
"}\n"
"\n"
"function renderContainers(list){\n"
"  const g=document.getElementById('containers-grid');\n"
"  if(!list.length){\n"
"    g.innerHTML='<div class=\"empty\"><h3>No containers</h3><p>Create one with: lochs create &lt;name&gt; -i freebsd:15</p></div>';\n"
"    return\n"
"  }\n"
"  g.innerHTML=list.map(c=>{\n"
"    const st=c.state||'unknown';\n"
"    const isRun=st==='running';\n"
"    return'<div class=\"card\" onclick=\"showDetail(\\''+esc(c.name)+'\\')\">' +\n"
"      '<div class=\"card-head\">' +\n"
"        '<span class=\"card-name\">'+esc(c.name)+'</span>' +\n"
"        '<span class=\"badge badge-'+esc(st)+'\">'+esc(st)+'</span>' +\n"
"      '</div>' +\n"
"      '<div class=\"card-body\">' +\n"
"        '<div class=\"field\"><span class=\"lbl\">Image</span><span class=\"val\">'+esc(c.image)+'</span></div>' +\n"
"        '<div class=\"field\"><span class=\"lbl\">IP</span><span class=\"val\">'+(esc(c.ip4_addr)||'-')+'</span></div>' +\n"
"        '<div class=\"field\"><span class=\"lbl\">Ports</span><span class=\"val\">'+fmtPorts(c.ports)+'</span></div>' +\n"
"        '<div class=\"field\"><span class=\"lbl\">'+(isRun?'Uptime':'Health')+'</span><span class=\"val\">'+(isRun?fmtUp(c.uptime_seconds):healthDot(c.health))+'</span></div>' +\n"
"        (isRun&&c.health&&c.health!=='none'?'<div class=\"field\"><span class=\"lbl\">Health</span><span class=\"val\">'+healthDot(c.health)+'</span></div>':'') +\n"
"      '</div>' +\n"
"      '<div class=\"card-actions\" onclick=\"event.stopPropagation()\">' +\n"
"        (isRun?'<button class=\"btn btn-stop\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'stop\\')\">Stop</button>'+\n"
"               '<button class=\"btn\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'restart\\')\">Restart</button>'\n"
"              :'<button class=\"btn btn-start\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'start\\')\">Start</button>'+\n"
"               '<button class=\"btn btn-danger\" onclick=\"doAction(\\''+esc(c.name)+'\\',\\'rm\\')\">Remove</button>') +\n"
"      '</div>' +\n"
"    '</div>'\n"
"  }).join('')\n"
"}\n"
"\n"
"async function doAction(name,act){\n"
"  if(act==='rm'&&!confirm('Remove container \"'+name+'\"?'))return;\n"
"  const btn=event.target;btn.disabled=true;btn.innerHTML='<span class=\"spinner\"></span>';\n"
"  const r=await api('/api/containers/'+encodeURIComponent(name)+'/'+act,{method:'POST'});\n"
"  if(r&&r.ok)toast(act+' '+name+': success',true);\n"
"  else toast('Error: '+(r?r.output:'request failed'),false);\n"
"  refresh();\n"
"  if(currentDetail===name)loadDetail(name)\n"
"}\n"
"\n"
"/* === Detail panel === */\n"
"async function showDetail(name){\n"
"  currentDetail=name;\n"
"  document.getElementById('d-name').textContent=name;\n"
"  document.getElementById('overlay').classList.add('active');\n"
"  document.getElementById('detail').classList.add('active');\n"
"  showDTab('info');\n"
"  loadDetail(name)\n"
"}\n"
"\n"
"function closeDetail(){\n"
"  currentDetail=null;\n"
"  document.getElementById('overlay').classList.remove('active');\n"
"  document.getElementById('detail').classList.remove('active');\n"
"  if(logInterval){clearInterval(logInterval);logInterval=null}\n"
"}\n"
"\n"
"async function loadDetail(name){\n"
"  const c=await api('/api/containers/'+encodeURIComponent(name));\n"
"  if(!c)return;\n"
"  const el=document.getElementById('d-info');\n"
"  const isRun=c.state==='running';\n"
"  el.innerHTML=\n"
"    '<div class=\"info-grid\">'+\n"
"    '<div class=\"info-item\"><div class=\"il\">State</div><div class=\"iv\"><span class=\"badge badge-'+esc(c.state)+'\">'+esc(c.state)+'</span></div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Image</div><div class=\"iv\">'+esc(c.image)+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">JID</div><div class=\"iv\">'+(c.jid||'-')+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">PID</div><div class=\"iv\">'+(c.pid||'-')+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Created</div><div class=\"iv\">'+fmtTime(c.created_at)+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Started</div><div class=\"iv\">'+fmtTime(c.started_at)+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">IP Address</div><div class=\"iv\">'+(esc(c.ip4_addr)||'-')+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Network</div><div class=\"iv\">'+(esc(c.network)||'-')+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Ports</div><div class=\"iv\">'+fmtPorts(c.ports)+'</div></div>'+\n"
"    '<div class=\"info-item\"><div class=\"il\">Storage</div><div class=\"iv\">'+(esc(c.storage_backend)||'overlay')+'</div></div>'+\n"
"    (c.cmd?'<div class=\"info-item info-full\"><div class=\"il\">CMD</div><div class=\"iv\" style=\"font-family:monospace\">'+esc(c.cmd)+'</div></div>':'') +\n"
"    (c.health&&c.health!=='none'?'<div class=\"info-item\"><div class=\"il\">Health</div><div class=\"iv\">'+healthDot(c.health)+'</div></div>':'') +\n"
"    (c.health_cmd?'<div class=\"info-item info-full\"><div class=\"il\">Health Check</div><div class=\"iv\" style=\"font-family:monospace\">'+esc(c.health_cmd)+'</div></div>':'') +\n"
"    '</div>'\n"
"}\n"
"\n"
"async function loadLogs(name){\n"
"  const d=await api('/api/logs/'+encodeURIComponent(name));\n"
"  const el=document.getElementById('d-logs');\n"
"  if(!d||!d.lines||!d.lines.length){\n"
"    el.innerHTML='<div class=\"empty\"><p>No logs available</p></div>';return\n"
"  }\n"
"  el.innerHTML='<div class=\"log-viewer\" id=\"log-box\">'+d.lines.map(l=>esc(l)).join('\\n')+'</div>';\n"
"  const box=document.getElementById('log-box');\n"
"  if(box)box.scrollTop=box.scrollHeight\n"
"}\n"
"\n"
"async function loadStats(name){\n"
"  const d=await api('/api/stats/'+encodeURIComponent(name));\n"
"  const el=document.getElementById('d-stats');\n"
"  if(!d){el.innerHTML='<div class=\"empty\"><p>No stats available</p></div>';return}\n"
"  const memPct=d.memory_limit_bytes>0?Math.round(d.memory_bytes/d.memory_limit_bytes*100):0;\n"
"  const barColor=memPct>90?'red':memPct>70?'yellow':'green';\n"
"  el.innerHTML=\n"
"    '<div class=\"stats-grid\">'+\n"
"    '<div class=\"stat-card\"><div class=\"stat-label\">CPU Time</div>'+\n"
"      '<div class=\"stat-value\">'+(d.cpu_usage_usec/1000000).toFixed(2)+'s</div></div>'+\n"
"    '<div class=\"stat-card\"><div class=\"stat-label\">Memory</div>'+\n"
"      '<div class=\"stat-value\">'+fmtBytes(d.memory_bytes)+'</div>'+\n"
"      '<div class=\"stat-sub\">/ '+fmtBytes(d.memory_limit_bytes)+'</div>'+\n"
"      (d.memory_limit_bytes>0?'<div class=\"stat-bar\"><div class=\"stat-bar-fill '+barColor+'\" style=\"width:'+memPct+'%\"></div></div>':'')+'</div>'+\n"
"    '<div class=\"stat-card\"><div class=\"stat-label\">Processes</div>'+\n"
"      '<div class=\"stat-value\">'+(d.pids||0)+'</div>'+\n"
"      (d.pids_limit>0?'<div class=\"stat-sub\">/ '+d.pids_limit+' max</div>':'')+'</div>'+\n"
"    '<div class=\"stat-card\"><div class=\"stat-label\">Swap</div>'+\n"
"      '<div class=\"stat-value\">'+fmtBytes(d.swap_bytes)+'</div></div>'+\n"
"    '</div>'\n"
"}\n"
"\n"
"function showDTab(tab){\n"
"  document.querySelectorAll('.dtab').forEach(t=>t.classList.remove('active'));\n"
"  document.querySelectorAll('.dcontent').forEach(t=>t.classList.remove('active'));\n"
"  event.target.classList.add('active');\n"
"  document.getElementById('d-'+tab).classList.add('active');\n"
"  if(logInterval){clearInterval(logInterval);logInterval=null}\n"
"  if(tab==='logs'&&currentDetail){\n"
"    loadLogs(currentDetail);\n"
"    logInterval=setInterval(()=>loadLogs(currentDetail),3000)\n"
"  }\n"
"  if(tab==='stats'&&currentDetail)loadStats(currentDetail);\n"
"  if(tab==='info'&&currentDetail)loadDetail(currentDetail)\n"
"}\n"
"\n"
"/* === Images === */\n"
"async function refreshImages(){\n"
"  const d=await api('/api/images');\n"
"  const g=document.getElementById('images-grid');\n"
"  if(!d||!d.images||!d.images.length){\n"
"    g.innerHTML='<div class=\"empty\"><h3>No images</h3><p>Pull one with: lochs pull freebsd:15</p></div>';return\n"
"  }\n"
"  g.innerHTML=d.images.map(i=>\n"
"    '<div class=\"list-card\">'+\n"
"      '<div><div class=\"list-name\">'+esc(i.repository)+':'+esc(i.tag)+'</div>'+\n"
"        '<div class=\"list-info\">'+\n"
"          '<span>ID: '+esc((i.id||'').substring(0,12))+'</span>'+\n"
"          '<span>Size: '+fmtBytes(i.size)+'</span>'+\n"
"          '<span>Pulled: '+fmtTime(i.pulled)+'</span>'+\n"
"        '</div></div>'+\n"
"    '</div>'\n"
"  ).join('')\n"
"}\n"
"\n"
"/* === Networks === */\n"
"async function refreshNetworks(){\n"
"  const d=await api('/api/networks');\n"
"  const g=document.getElementById('networks-grid');\n"
"  if(!d||!d.networks||!d.networks.length){\n"
"    g.innerHTML='<div class=\"empty\"><h3>No networks</h3><p>Create one with: lochs network create &lt;name&gt;</p></div>';return\n"
"  }\n"
"  g.innerHTML=d.networks.map(n=>\n"
"    '<div class=\"list-card\">'+\n"
"      '<div><div class=\"list-name\">'+esc(n.name)+'</div>'+\n"
"        '<div class=\"list-info\">'+\n"
"          '<span>Subnet: '+esc(n.subnet)+'</span>'+\n"
"          '<span>Gateway: '+esc(n.gateway)+'</span>'+\n"
"          '<span>Bridge: '+esc(n.bridge)+'</span>'+\n"
"        '</div></div>'+\n"
"      '<span class=\"badge '+(n.active?'badge-running':'badge-stopped')+'\">'+(n.active?'active':'inactive')+'</span>'+\n"
"    '</div>'\n"
"  ).join('')\n"
"}\n"
"\n"
"/* === Tab switching === */\n"
"function showTab(tab){\n"
"  document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));\n"
"  document.querySelectorAll('.tab-content').forEach(t=>t.classList.remove('active'));\n"
"  event.target.classList.add('active');\n"
"  document.getElementById('t-'+tab).classList.add('active');\n"
"  if(tab==='images')refreshImages();\n"
"  if(tab==='networks')refreshNetworks()\n"
"}\n"
"\n"
"/* Auto-refresh */\n"
"refresh();\n"
"setInterval(refresh,3000);\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* LOCHS_DASHBOARD_HTML_H */
